[package]
authors                = ["Tracel Technologies Inc.", "McCoy R. Becker", "Yota Toyama", "Edgar Luque"]
categories             = ["external-ffi-bindings"]
description            = "Rust bindings for MLIR C API used by CubeCL."
edition.workspace      = true
keywords               = ["cubecl", "llvm", "mlir", "bindings"]
license                = "MIT"
name                   = "tracel-mlir-sys"
readme.workspace       = true
repository             = "https://github.com/tracel-ai/tracel-llvm/tree/main/crates/tracel-mlir-sys"
rust-version.workspace = true
version.workspace      = true

[features]
default = []
llvm_20_1_4 = []

[build-dependencies]
tracel-llvm-bundler = { path = "../tracel-llvm-bundler", version = "20.1.4-5" }