[package]
authors = ["Tracel Technologies Inc."]
categories = ["api-bindings", "external-ffi-bindings"]
description = "Rust bindings for LLVM libraries used by CubeCL."
edition.workspace = true
keywords = ["cubecl", "llvm", "mlir", "bindings"]
license.workspace = true
name = "tracel-llvm"
readme.workspace = true
repository = "https://github.com/tracel-ai/tracel-llvm/tree/main/crates/tracel-llvm"
rust-version.workspace = true
version.workspace = true

[features]
mlir-helpers = ["tracel-mlir-rs/helpers"]
mlir-ods-dialects = ["tracel-mlir-rs/ods-dialects"]

[dependencies]
tracel-mlir-rs = { path = "../tracel-mlir-rs", version = "22.1.4-1" }
tracel-mlir-sys = { path = "../tracel-mlir-sys", version = "22.1.4-1" }
