[package]
name = "tracel-llvm"
version = "0.1.0"
edition = "2024"

[dependencies]
melior = { git = "https://github.com/marcantoinem/melior", rev = "c51378d9ff5ddee5396d1b91e6b2e3b10b99665c", features = ["ods-dialects", "helpers"] }
