[package]
name = "tracel-llvm"
version = "0.1.0"
edition = "2024"

[dependencies]
melior = { git = "https://github.com/marcantoinem/melior", rev = "575ac28fb1a3ffc5c1c833105a2cfb4e9026a91d", features = ["ods-dialects"] }
