[package]
name = "tracel-llvm"
version = "0.1.0"
edition = "2024"

[dependencies]
melior = { git = "https://github.com/marcantoinem/melior", rev = "ef9aefa4438b52600e8ba06f1d882c399f386168", features = ["ods-dialects"] }
