/* Wrappers around the LLVM-C target initialization functions.
 *
 * `llvm-c/Target.h` declares the `LLVMInitialize*` functions as `static inline`
 * bodies generated by macros, so they cannot be bound to directly from Rust.
 * `llvm-sys` normally compiles equivalent wrappers in its own build script, but
 * we build it with `disable-alltargets-init` so that its build script never
 * needs to locate `llvm-config`, and provide the symbols from here instead.
 *
 * The symbol names must stay in sync with the `extern "C"` block in
 * `llvm_sys::target`.
 */
#include <llvm-c/Target.h>

void LLVM_InitializeAllTargetInfos(void) {
    LLVMInitializeAllTargetInfos();
}

void LLVM_InitializeAllTargets(void) {
    LLVMInitializeAllTargets();
}

void LLVM_InitializeAllTargetMCs(void) {
    LLVMInitializeAllTargetMCs();
}

void LLVM_InitializeAllAsmPrinters(void) {
    LLVMInitializeAllAsmPrinters();
}

void LLVM_InitializeAllAsmParsers(void) {
    LLVMInitializeAllAsmParsers();
}

void LLVM_InitializeAllDisassemblers(void) {
    LLVMInitializeAllDisassemblers();
}

/* These return a non-zero value on failure. */

LLVMBool LLVM_InitializeNativeTarget(void) {
    return LLVMInitializeNativeTarget();
}

LLVMBool LLVM_InitializeNativeAsmParser(void) {
    return LLVMInitializeNativeAsmParser();
}

LLVMBool LLVM_InitializeNativeAsmPrinter(void) {
    return LLVMInitializeNativeAsmPrinter();
}

LLVMBool LLVM_InitializeNativeDisassembler(void) {
    return LLVMInitializeNativeDisassembler();
}
