[package]
edition = "2024"
name = "xtask"
version = "0.0.0"

[dependencies]
bindgen = { version = "0.72.1" }
tracel-llvm-bundler = { path = "../crates/tracel-llvm-bundler", features = [
    "xtask",
] }

chrono = "0.4.42"
dirs = "6.0.0"
fs2 = "0.4.3"
log = "0.4.28"
reqwest = { version = "0.12.23", features = ["blocking", "rustls-tls", "http2"], default-features = false }
strum = "0.27.2"
tracel-xtask = "=4.17.2"
which = "8.0.0"
