[package]
authors                = ["Tracel Technologies Inc.", "Daan Vanoverloop", "Yota Toyama", "Edgar Luque"]
categories             = ["development-tools::ffi"]
description            = "Safe Rust bindings for TableGen used by CubeCL."
edition.workspace      = true
keywords               = ["cubecl", "llvm", "tablegen", "bindings", "wrapper"]
license                = "MIT OR Apache-2.0"
name                   = "tracel-tblgen"
readme.workspace       = true
repository             = "https://github.com/tracel-ai/tracel-llvm/tree/main/crates/tracel-tblgen-rs"
rust-version.workspace = true
version.workspace      = true
exclude = ["doc/"]

[features]

[dependencies]
thiserror = "2.0.16"
paste = "1.0.15"

[build-dependencies]
bindgen = "0.71.1"
cc = "1.2.37"
tracel-llvm-bundler = { path = "../tracel-llvm-bundler" }
