/* automatically generated by rust-bindgen 0.72.1 */

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]

pub const _GLIBCXX_CSTDDEF: u32 = 1;
pub const _GLIBCXX_CXX_CONFIG_H: u32 = 1;
pub const _GLIBCXX_RELEASE: u32 = 11;
pub const __GLIBCXX__: u32 = 20230528;
pub const _GLIBCXX_HAVE_ATTRIBUTE_VISIBILITY: u32 = 1;
pub const _GLIBCXX_USE_DEPRECATED: u32 = 1;
pub const _GLIBCXX_EXTERN_TEMPLATE: u32 = 1;
pub const _GLIBCXX_USE_DUAL_ABI: u32 = 1;
pub const _GLIBCXX_USE_CXX11_ABI: u32 = 1;
pub const _GLIBCXX_INLINE_VERSION: u32 = 0;
pub const _GLIBCXX_USE_ALLOCATOR_NEW: u32 = 1;
pub const _GLIBCXX_OS_DEFINES: u32 = 1;
pub const __NO_CTYPE: u32 = 1;
pub const _FEATURES_H: u32 = 1;
pub const _ISOC95_SOURCE: u32 = 1;
pub const _ISOC99_SOURCE: u32 = 1;
pub const _ISOC11_SOURCE: u32 = 1;
pub const _ISOC2X_SOURCE: u32 = 1;
pub const _POSIX_SOURCE: u32 = 1;
pub const _POSIX_C_SOURCE: u32 = 200809;
pub const _XOPEN_SOURCE: u32 = 700;
pub const _XOPEN_SOURCE_EXTENDED: u32 = 1;
pub const _LARGEFILE64_SOURCE: u32 = 1;
pub const _DEFAULT_SOURCE: u32 = 1;
pub const _ATFILE_SOURCE: u32 = 1;
pub const _DYNAMIC_STACK_SIZE_SOURCE: u32 = 1;
pub const __GLIBC_USE_ISOC2X: u32 = 1;
pub const __USE_ISOC11: u32 = 1;
pub const __USE_ISOC99: u32 = 1;
pub const __USE_ISOC95: u32 = 1;
pub const __USE_ISOCXX11: u32 = 1;
pub const __USE_POSIX: u32 = 1;
pub const __USE_POSIX2: u32 = 1;
pub const __USE_POSIX199309: u32 = 1;
pub const __USE_POSIX199506: u32 = 1;
pub const __USE_XOPEN2K: u32 = 1;
pub const __USE_XOPEN2K8: u32 = 1;
pub const __USE_XOPEN: u32 = 1;
pub const __USE_XOPEN_EXTENDED: u32 = 1;
pub const __USE_UNIX98: u32 = 1;
pub const _LARGEFILE_SOURCE: u32 = 1;
pub const __USE_XOPEN2K8XSI: u32 = 1;
pub const __USE_XOPEN2KXSI: u32 = 1;
pub const __USE_LARGEFILE: u32 = 1;
pub const __USE_LARGEFILE64: u32 = 1;
pub const __WORDSIZE: u32 = 64;
pub const __WORDSIZE_TIME64_COMPAT32: u32 = 0;
pub const __TIMESIZE: u32 = 64;
pub const __USE_MISC: u32 = 1;
pub const __USE_ATFILE: u32 = 1;
pub const __USE_DYNAMIC_STACK_SIZE: u32 = 1;
pub const __USE_GNU: u32 = 1;
pub const __USE_FORTIFY_LEVEL: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_GETS: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_SCANF: u32 = 0;
pub const _STDC_PREDEF_H: u32 = 1;
pub const __STDC_IEC_559__: u32 = 1;
pub const __STDC_IEC_60559_BFP__: u32 = 201404;
pub const __STDC_IEC_559_COMPLEX__: u32 = 1;
pub const __STDC_IEC_60559_COMPLEX__: u32 = 201404;
pub const __STDC_ISO_10646__: u32 = 201706;
pub const __GNU_LIBRARY__: u32 = 6;
pub const __GLIBC__: u32 = 2;
pub const __GLIBC_MINOR__: u32 = 35;
pub const _SYS_CDEFS_H: u32 = 1;
pub const __glibc_c99_flexarr_available: u32 = 1;
pub const __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI: u32 = 0;
pub const __HAVE_GENERIC_SELECTION: u32 = 0;
pub const _GLIBCXX_GTHREAD_USE_WEAK: u32 = 0;
pub const _GLIBCXX_CPU_DEFINES: u32 = 1;
pub const _GLIBCXX_USE_STD_SPEC_FUNCS: u32 = 1;
pub const _GLIBCXX_FAST_MATH: u32 = 0;
pub const _GLIBCXX_FLOAT_IS_IEEE_BINARY32: u32 = 1;
pub const _GLIBCXX_DOUBLE_IS_IEEE_BINARY64: u32 = 1;
pub const _GLIBCXX_HAVE_BUILTIN_HAS_UNIQ_OBJ_REP: u32 = 1;
pub const _GLIBCXX_HAVE_BUILTIN_IS_AGGREGATE: u32 = 1;
pub const _GLIBCXX_HAVE_BUILTIN_IS_CONSTANT_EVALUATED: u32 = 1;
pub const _GLIBCXX_HAVE_BUILTIN_IS_SAME: u32 = 1;
pub const _GLIBCXX_HAVE_BUILTIN_LAUNDER: u32 = 1;
pub const _PSTL_VERSION: u32 = 12000;
pub const _PSTL_VERSION_MAJOR: u32 = 12;
pub const _PSTL_VERSION_MINOR: u32 = 0;
pub const _PSTL_VERSION_PATCH: u32 = 0;
pub const _PSTL_USAGE_WARNINGS: u32 = 0;
pub const _PSTL_UDR_PRESENT: u32 = 0;
pub const _PSTL_PRAGMA_LOCATION: &[u8; 26] = b" [Parallel STL message]: \0";
pub const _GLIBCXX_HAVE_ACOSF: u32 = 1;
pub const _GLIBCXX_HAVE_ACOSL: u32 = 1;
pub const _GLIBCXX_HAVE_ALIGNED_ALLOC: u32 = 1;
pub const _GLIBCXX_HAVE_ARPA_INET_H: u32 = 1;
pub const _GLIBCXX_HAVE_ASINF: u32 = 1;
pub const _GLIBCXX_HAVE_ASINL: u32 = 1;
pub const _GLIBCXX_HAVE_AS_SYMVER_DIRECTIVE: u32 = 1;
pub const _GLIBCXX_HAVE_ATAN2F: u32 = 1;
pub const _GLIBCXX_HAVE_ATAN2L: u32 = 1;
pub const _GLIBCXX_HAVE_ATANF: u32 = 1;
pub const _GLIBCXX_HAVE_ATANL: u32 = 1;
pub const _GLIBCXX_HAVE_ATOMIC_LOCK_POLICY: u32 = 1;
pub const _GLIBCXX_HAVE_AT_QUICK_EXIT: u32 = 1;
pub const _GLIBCXX_HAVE_CEILF: u32 = 1;
pub const _GLIBCXX_HAVE_CEILL: u32 = 1;
pub const _GLIBCXX_HAVE_COMPLEX_H: u32 = 1;
pub const _GLIBCXX_HAVE_COSF: u32 = 1;
pub const _GLIBCXX_HAVE_COSHF: u32 = 1;
pub const _GLIBCXX_HAVE_COSHL: u32 = 1;
pub const _GLIBCXX_HAVE_COSL: u32 = 1;
pub const _GLIBCXX_HAVE_DIRENT_H: u32 = 1;
pub const _GLIBCXX_HAVE_DLFCN_H: u32 = 1;
pub const _GLIBCXX_HAVE_ENDIAN_H: u32 = 1;
pub const _GLIBCXX_HAVE_EXCEPTION_PTR_SINCE_GCC46: u32 = 1;
pub const _GLIBCXX_HAVE_EXECINFO_H: u32 = 1;
pub const _GLIBCXX_HAVE_EXPF: u32 = 1;
pub const _GLIBCXX_HAVE_EXPL: u32 = 1;
pub const _GLIBCXX_HAVE_FABSF: u32 = 1;
pub const _GLIBCXX_HAVE_FABSL: u32 = 1;
pub const _GLIBCXX_HAVE_FCNTL_H: u32 = 1;
pub const _GLIBCXX_HAVE_FENV_H: u32 = 1;
pub const _GLIBCXX_HAVE_FINITE: u32 = 1;
pub const _GLIBCXX_HAVE_FINITEF: u32 = 1;
pub const _GLIBCXX_HAVE_FINITEL: u32 = 1;
pub const _GLIBCXX_HAVE_FLOAT_H: u32 = 1;
pub const _GLIBCXX_HAVE_FLOORF: u32 = 1;
pub const _GLIBCXX_HAVE_FLOORL: u32 = 1;
pub const _GLIBCXX_HAVE_FMODF: u32 = 1;
pub const _GLIBCXX_HAVE_FMODL: u32 = 1;
pub const _GLIBCXX_HAVE_FREXPF: u32 = 1;
pub const _GLIBCXX_HAVE_FREXPL: u32 = 1;
pub const _GLIBCXX_HAVE_GETIPINFO: u32 = 1;
pub const _GLIBCXX_HAVE_GETS: u32 = 1;
pub const _GLIBCXX_HAVE_HYPOT: u32 = 1;
pub const _GLIBCXX_HAVE_HYPOTF: u32 = 1;
pub const _GLIBCXX_HAVE_HYPOTL: u32 = 1;
pub const _GLIBCXX_HAVE_ICONV: u32 = 1;
pub const _GLIBCXX_HAVE_INT64_T: u32 = 1;
pub const _GLIBCXX_HAVE_INT64_T_LONG: u32 = 1;
pub const _GLIBCXX_HAVE_INTTYPES_H: u32 = 1;
pub const _GLIBCXX_HAVE_ISINFF: u32 = 1;
pub const _GLIBCXX_HAVE_ISINFL: u32 = 1;
pub const _GLIBCXX_HAVE_ISNANF: u32 = 1;
pub const _GLIBCXX_HAVE_ISNANL: u32 = 1;
pub const _GLIBCXX_HAVE_ISWBLANK: u32 = 1;
pub const _GLIBCXX_HAVE_LC_MESSAGES: u32 = 1;
pub const _GLIBCXX_HAVE_LDEXPF: u32 = 1;
pub const _GLIBCXX_HAVE_LDEXPL: u32 = 1;
pub const _GLIBCXX_HAVE_LIBINTL_H: u32 = 1;
pub const _GLIBCXX_HAVE_LIMIT_AS: u32 = 1;
pub const _GLIBCXX_HAVE_LIMIT_DATA: u32 = 1;
pub const _GLIBCXX_HAVE_LIMIT_FSIZE: u32 = 1;
pub const _GLIBCXX_HAVE_LIMIT_RSS: u32 = 1;
pub const _GLIBCXX_HAVE_LIMIT_VMEM: u32 = 0;
pub const _GLIBCXX_HAVE_LINK: u32 = 1;
pub const _GLIBCXX_HAVE_LINUX_FUTEX: u32 = 1;
pub const _GLIBCXX_HAVE_LINUX_RANDOM_H: u32 = 1;
pub const _GLIBCXX_HAVE_LINUX_TYPES_H: u32 = 1;
pub const _GLIBCXX_HAVE_LOCALE_H: u32 = 1;
pub const _GLIBCXX_HAVE_LOG10F: u32 = 1;
pub const _GLIBCXX_HAVE_LOG10L: u32 = 1;
pub const _GLIBCXX_HAVE_LOGF: u32 = 1;
pub const _GLIBCXX_HAVE_LOGL: u32 = 1;
pub const _GLIBCXX_HAVE_MBSTATE_T: u32 = 1;
pub const _GLIBCXX_HAVE_MEMALIGN: u32 = 1;
pub const _GLIBCXX_HAVE_MEMORY_H: u32 = 1;
pub const _GLIBCXX_HAVE_MODF: u32 = 1;
pub const _GLIBCXX_HAVE_MODFF: u32 = 1;
pub const _GLIBCXX_HAVE_MODFL: u32 = 1;
pub const _GLIBCXX_HAVE_NETDB_H: u32 = 1;
pub const _GLIBCXX_HAVE_NETINET_IN_H: u32 = 1;
pub const _GLIBCXX_HAVE_NETINET_TCP_H: u32 = 1;
pub const _GLIBCXX_HAVE_POLL: u32 = 1;
pub const _GLIBCXX_HAVE_POLL_H: u32 = 1;
pub const _GLIBCXX_HAVE_POSIX_MEMALIGN: u32 = 1;
pub const _GLIBCXX_HAVE_POSIX_SEMAPHORE: u32 = 1;
pub const _GLIBCXX_HAVE_POWF: u32 = 1;
pub const _GLIBCXX_HAVE_POWL: u32 = 1;
pub const _GLIBCXX_HAVE_QUICK_EXIT: u32 = 1;
pub const _GLIBCXX_HAVE_READLINK: u32 = 1;
pub const _GLIBCXX_HAVE_SECURE_GETENV: u32 = 1;
pub const _GLIBCXX_HAVE_SETENV: u32 = 1;
pub const _GLIBCXX_HAVE_SINCOS: u32 = 1;
pub const _GLIBCXX_HAVE_SINCOSF: u32 = 1;
pub const _GLIBCXX_HAVE_SINCOSL: u32 = 1;
pub const _GLIBCXX_HAVE_SINF: u32 = 1;
pub const _GLIBCXX_HAVE_SINHF: u32 = 1;
pub const _GLIBCXX_HAVE_SINHL: u32 = 1;
pub const _GLIBCXX_HAVE_SINL: u32 = 1;
pub const _GLIBCXX_HAVE_SOCKATMARK: u32 = 1;
pub const _GLIBCXX_HAVE_SQRTF: u32 = 1;
pub const _GLIBCXX_HAVE_SQRTL: u32 = 1;
pub const _GLIBCXX_HAVE_STDALIGN_H: u32 = 1;
pub const _GLIBCXX_HAVE_STDBOOL_H: u32 = 1;
pub const _GLIBCXX_HAVE_STDINT_H: u32 = 1;
pub const _GLIBCXX_HAVE_STDLIB_H: u32 = 1;
pub const _GLIBCXX_HAVE_STRERROR_L: u32 = 1;
pub const _GLIBCXX_HAVE_STRERROR_R: u32 = 1;
pub const _GLIBCXX_HAVE_STRINGS_H: u32 = 1;
pub const _GLIBCXX_HAVE_STRING_H: u32 = 1;
pub const _GLIBCXX_HAVE_STRTOF: u32 = 1;
pub const _GLIBCXX_HAVE_STRTOLD: u32 = 1;
pub const _GLIBCXX_HAVE_STRUCT_DIRENT_D_TYPE: u32 = 1;
pub const _GLIBCXX_HAVE_STRXFRM_L: u32 = 1;
pub const _GLIBCXX_HAVE_SYMLINK: u32 = 1;
pub const _GLIBCXX_HAVE_SYMVER_SYMBOL_RENAMING_RUNTIME_SUPPORT: u32 = 1;
pub const _GLIBCXX_HAVE_SYS_IOCTL_H: u32 = 1;
pub const _GLIBCXX_HAVE_SYS_IPC_H: u32 = 1;
pub const _GLIBCXX_HAVE_SYS_PARAM_H: u32 = 1;
pub const _GLIBCXX_HAVE_SYS_RESOURCE_H: u32 = 1;
pub const _GLIBCXX_HAVE_SYS_SDT_H: u32 = 1;
pub const _GLIBCXX_HAVE_SYS_SEM_H: u32 = 1;
pub const _GLIBCXX_HAVE_SYS_SOCKET_H: u32 = 1;
pub const _GLIBCXX_HAVE_SYS_STATVFS_H: u32 = 1;
pub const _GLIBCXX_HAVE_SYS_STAT_H: u32 = 1;
pub const _GLIBCXX_HAVE_SYS_SYSINFO_H: u32 = 1;
pub const _GLIBCXX_HAVE_SYS_TIME_H: u32 = 1;
pub const _GLIBCXX_HAVE_SYS_TYPES_H: u32 = 1;
pub const _GLIBCXX_HAVE_SYS_UIO_H: u32 = 1;
pub const _GLIBCXX_HAVE_S_ISREG: u32 = 1;
pub const _GLIBCXX_HAVE_TANF: u32 = 1;
pub const _GLIBCXX_HAVE_TANHF: u32 = 1;
pub const _GLIBCXX_HAVE_TANHL: u32 = 1;
pub const _GLIBCXX_HAVE_TANL: u32 = 1;
pub const _GLIBCXX_HAVE_TGMATH_H: u32 = 1;
pub const _GLIBCXX_HAVE_TIMESPEC_GET: u32 = 1;
pub const _GLIBCXX_HAVE_TLS: u32 = 1;
pub const _GLIBCXX_HAVE_TRUNCATE: u32 = 1;
pub const _GLIBCXX_HAVE_UCHAR_H: u32 = 1;
pub const _GLIBCXX_HAVE_UNISTD_H: u32 = 1;
pub const _GLIBCXX_HAVE_USELOCALE: u32 = 1;
pub const _GLIBCXX_HAVE_UTIME_H: u32 = 1;
pub const _GLIBCXX_HAVE_VFWSCANF: u32 = 1;
pub const _GLIBCXX_HAVE_VSWSCANF: u32 = 1;
pub const _GLIBCXX_HAVE_VWSCANF: u32 = 1;
pub const _GLIBCXX_HAVE_WCHAR_H: u32 = 1;
pub const _GLIBCXX_HAVE_WCSTOF: u32 = 1;
pub const _GLIBCXX_HAVE_WCTYPE_H: u32 = 1;
pub const _GLIBCXX_HAVE_WRITEV: u32 = 1;
pub const _GLIBCXX_HAVE___CXA_THREAD_ATEXIT_IMPL: u32 = 1;
pub const _GLIBCXX_LT_OBJDIR: &[u8; 7] = b".libs/\0";
pub const _GLIBCXX_PACKAGE_BUGREPORT: &[u8; 1] = b"\0";
pub const _GLIBCXX_PACKAGE_NAME: &[u8; 15] = b"package-unused\0";
pub const _GLIBCXX_PACKAGE_STRING: &[u8; 30] = b"package-unused version-unused\0";
pub const _GLIBCXX_PACKAGE_TARNAME: &[u8; 10] = b"libstdc++\0";
pub const _GLIBCXX_PACKAGE_URL: &[u8; 1] = b"\0";
pub const _GLIBCXX_PACKAGE__GLIBCXX_VERSION: &[u8; 15] = b"version-unused\0";
pub const _GLIBCXX_STDC_HEADERS: u32 = 1;
pub const _GLIBCXX_DARWIN_USE_64_BIT_INODE: u32 = 1;
pub const _GLIBCXX11_USE_C99_COMPLEX: u32 = 1;
pub const _GLIBCXX11_USE_C99_MATH: u32 = 1;
pub const _GLIBCXX11_USE_C99_STDIO: u32 = 1;
pub const _GLIBCXX11_USE_C99_STDLIB: u32 = 1;
pub const _GLIBCXX11_USE_C99_WCHAR: u32 = 1;
pub const _GLIBCXX98_USE_C99_COMPLEX: u32 = 1;
pub const _GLIBCXX98_USE_C99_MATH: u32 = 1;
pub const _GLIBCXX98_USE_C99_STDIO: u32 = 1;
pub const _GLIBCXX98_USE_C99_STDLIB: u32 = 1;
pub const _GLIBCXX98_USE_C99_WCHAR: u32 = 1;
pub const _GLIBCXX_ATOMIC_BUILTINS: u32 = 1;
pub const _GLIBCXX_FULLY_DYNAMIC_STRING: u32 = 0;
pub const _GLIBCXX_HAS_GTHREADS: u32 = 1;
pub const _GLIBCXX_HOSTED: u32 = 1;
pub const _GLIBCXX_RES_LIMITS: u32 = 1;
pub const _GLIBCXX_STDIO_EOF: i32 = -1;
pub const _GLIBCXX_STDIO_SEEK_CUR: u32 = 1;
pub const _GLIBCXX_STDIO_SEEK_END: u32 = 2;
pub const _GLIBCXX_SYMVER: u32 = 1;
pub const _GLIBCXX_SYMVER_GNU: u32 = 1;
pub const _GLIBCXX_USE_C11_UCHAR_CXX11: u32 = 1;
pub const _GLIBCXX_USE_C99: u32 = 1;
pub const _GLIBCXX_USE_C99_COMPLEX_TR1: u32 = 1;
pub const _GLIBCXX_USE_C99_CTYPE_TR1: u32 = 1;
pub const _GLIBCXX_USE_C99_FENV_TR1: u32 = 1;
pub const _GLIBCXX_USE_C99_INTTYPES_TR1: u32 = 1;
pub const _GLIBCXX_USE_C99_INTTYPES_WCHAR_T_TR1: u32 = 1;
pub const _GLIBCXX_USE_C99_MATH_TR1: u32 = 1;
pub const _GLIBCXX_USE_C99_STDINT_TR1: u32 = 1;
pub const _GLIBCXX_USE_CLOCK_MONOTONIC: u32 = 1;
pub const _GLIBCXX_USE_CLOCK_REALTIME: u32 = 1;
pub const _GLIBCXX_USE_DEV_RANDOM: u32 = 1;
pub const _GLIBCXX_USE_FCHMOD: u32 = 1;
pub const _GLIBCXX_USE_FCHMODAT: u32 = 1;
pub const _GLIBCXX_USE_GETTIMEOFDAY: u32 = 1;
pub const _GLIBCXX_USE_GET_NPROCS: u32 = 1;
pub const _GLIBCXX_USE_INT128: u32 = 1;
pub const _GLIBCXX_USE_LFS: u32 = 1;
pub const _GLIBCXX_USE_LONG_LONG: u32 = 1;
pub const _GLIBCXX_USE_LSTAT: u32 = 1;
pub const _GLIBCXX_USE_NANOSLEEP: u32 = 1;
pub const _GLIBCXX_USE_NLS: u32 = 1;
pub const _GLIBCXX_USE_PTHREAD_COND_CLOCKWAIT: u32 = 1;
pub const _GLIBCXX_USE_PTHREAD_MUTEX_CLOCKLOCK: u32 = 1;
pub const _GLIBCXX_USE_PTHREAD_RWLOCK_CLOCKLOCK: u32 = 1;
pub const _GLIBCXX_USE_PTHREAD_RWLOCK_T: u32 = 1;
pub const _GLIBCXX_USE_RANDOM_TR1: u32 = 1;
pub const _GLIBCXX_USE_REALPATH: u32 = 1;
pub const _GLIBCXX_USE_SCHED_YIELD: u32 = 1;
pub const _GLIBCXX_USE_SC_NPROCESSORS_ONLN: u32 = 1;
pub const _GLIBCXX_USE_SENDFILE: u32 = 1;
pub const _GLIBCXX_USE_ST_MTIM: u32 = 1;
pub const _GLIBCXX_USE_TMPNAM: u32 = 1;
pub const _GLIBCXX_USE_UTIME: u32 = 1;
pub const _GLIBCXX_USE_UTIMENSAT: u32 = 1;
pub const _GLIBCXX_USE_WCHAR_T: u32 = 1;
pub const _GLIBCXX_VERBOSE: u32 = 1;
pub const _GTHREAD_USE_MUTEX_TIMEDLOCK: u32 = 1;
pub const __cpp_lib_byte: u32 = 201603;
pub const _GLIBCXX_CSTDINT: u32 = 1;
pub const _STDINT_H: u32 = 1;
pub const __GLIBC_USE_LIB_EXT2: u32 = 1;
pub const __GLIBC_USE_IEC_60559_BFP_EXT: u32 = 1;
pub const __GLIBC_USE_IEC_60559_BFP_EXT_C2X: u32 = 1;
pub const __GLIBC_USE_IEC_60559_EXT: u32 = 1;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT: u32 = 1;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT_C2X: u32 = 1;
pub const __GLIBC_USE_IEC_60559_TYPES_EXT: u32 = 1;
pub const _BITS_TYPES_H: u32 = 1;
pub const _BITS_TYPESIZES_H: u32 = 1;
pub const __OFF_T_MATCHES_OFF64_T: u32 = 1;
pub const __INO_T_MATCHES_INO64_T: u32 = 1;
pub const __RLIM_T_MATCHES_RLIM64_T: u32 = 1;
pub const __STATFS_MATCHES_STATFS64: u32 = 1;
pub const __FD_SETSIZE: u32 = 1024;
pub const _BITS_TIME64_H: u32 = 1;
pub const _BITS_WCHAR_H: u32 = 1;
pub const _BITS_STDINT_INTN_H: u32 = 1;
pub const _BITS_STDINT_UINTN_H: u32 = 1;
pub const INT8_MIN: i32 = -128;
pub const INT16_MIN: i32 = -32768;
pub const INT32_MIN: i32 = -2147483648;
pub const INT8_MAX: u32 = 127;
pub const INT16_MAX: u32 = 32767;
pub const INT32_MAX: u32 = 2147483647;
pub const UINT8_MAX: u32 = 255;
pub const UINT16_MAX: u32 = 65535;
pub const UINT32_MAX: u32 = 4294967295;
pub const INT_LEAST8_MIN: i32 = -128;
pub const INT_LEAST16_MIN: i32 = -32768;
pub const INT_LEAST32_MIN: i32 = -2147483648;
pub const INT_LEAST8_MAX: u32 = 127;
pub const INT_LEAST16_MAX: u32 = 32767;
pub const INT_LEAST32_MAX: u32 = 2147483647;
pub const UINT_LEAST8_MAX: u32 = 255;
pub const UINT_LEAST16_MAX: u32 = 65535;
pub const UINT_LEAST32_MAX: u32 = 4294967295;
pub const INT_FAST8_MIN: i32 = -128;
pub const INT_FAST16_MIN: i64 = -9223372036854775808;
pub const INT_FAST32_MIN: i64 = -9223372036854775808;
pub const INT_FAST8_MAX: u32 = 127;
pub const INT_FAST16_MAX: u64 = 9223372036854775807;
pub const INT_FAST32_MAX: u64 = 9223372036854775807;
pub const UINT_FAST8_MAX: u32 = 255;
pub const UINT_FAST16_MAX: i32 = -1;
pub const UINT_FAST32_MAX: i32 = -1;
pub const INTPTR_MIN: i64 = -9223372036854775808;
pub const INTPTR_MAX: u64 = 9223372036854775807;
pub const UINTPTR_MAX: i32 = -1;
pub const PTRDIFF_MIN: i64 = -9223372036854775808;
pub const PTRDIFF_MAX: u64 = 9223372036854775807;
pub const SIG_ATOMIC_MIN: i32 = -2147483648;
pub const SIG_ATOMIC_MAX: u32 = 2147483647;
pub const SIZE_MAX: i32 = -1;
pub const WINT_MIN: u32 = 0;
pub const WINT_MAX: u32 = 4294967295;
pub const INT8_WIDTH: u32 = 8;
pub const UINT8_WIDTH: u32 = 8;
pub const INT16_WIDTH: u32 = 16;
pub const UINT16_WIDTH: u32 = 16;
pub const INT32_WIDTH: u32 = 32;
pub const UINT32_WIDTH: u32 = 32;
pub const INT64_WIDTH: u32 = 64;
pub const UINT64_WIDTH: u32 = 64;
pub const INT_LEAST8_WIDTH: u32 = 8;
pub const UINT_LEAST8_WIDTH: u32 = 8;
pub const INT_LEAST16_WIDTH: u32 = 16;
pub const UINT_LEAST16_WIDTH: u32 = 16;
pub const INT_LEAST32_WIDTH: u32 = 32;
pub const UINT_LEAST32_WIDTH: u32 = 32;
pub const INT_LEAST64_WIDTH: u32 = 64;
pub const UINT_LEAST64_WIDTH: u32 = 64;
pub const INT_FAST8_WIDTH: u32 = 8;
pub const UINT_FAST8_WIDTH: u32 = 8;
pub const INT_FAST16_WIDTH: u32 = 64;
pub const UINT_FAST16_WIDTH: u32 = 64;
pub const INT_FAST32_WIDTH: u32 = 64;
pub const UINT_FAST32_WIDTH: u32 = 64;
pub const INT_FAST64_WIDTH: u32 = 64;
pub const UINT_FAST64_WIDTH: u32 = 64;
pub const INTPTR_WIDTH: u32 = 64;
pub const UINTPTR_WIDTH: u32 = 64;
pub const INTMAX_WIDTH: u32 = 64;
pub const UINTMAX_WIDTH: u32 = 64;
pub const PTRDIFF_WIDTH: u32 = 64;
pub const SIG_ATOMIC_WIDTH: u32 = 32;
pub const SIZE_WIDTH: u32 = 64;
pub const WCHAR_WIDTH: u32 = 32;
pub const WINT_WIDTH: u32 = 32;
pub type std_nullptr_t = *const ::std::os::raw::c_void;
pub mod std_byte {
    pub type Type = ::std::os::raw::c_uchar;
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct std___byte_operand {
    pub _address: u8,
}
pub type std___byte_op_t = std___byte_operand;
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Default, Copy, Clone)]
pub struct max_align_t {
    pub __clang_max_align_nonce1: ::std::os::raw::c_longlong,
    pub __bindgen_padding_0: u64,
    pub __clang_max_align_nonce2: u128,
}
pub type __u_char = ::std::os::raw::c_uchar;
pub type __u_short = ::std::os::raw::c_ushort;
pub type __u_int = ::std::os::raw::c_uint;
pub type __u_long = ::std::os::raw::c_ulong;
pub type __int8_t = ::std::os::raw::c_schar;
pub type __uint8_t = ::std::os::raw::c_uchar;
pub type __int16_t = ::std::os::raw::c_short;
pub type __uint16_t = ::std::os::raw::c_ushort;
pub type __int32_t = ::std::os::raw::c_int;
pub type __uint32_t = ::std::os::raw::c_uint;
pub type __int64_t = ::std::os::raw::c_long;
pub type __uint64_t = ::std::os::raw::c_ulong;
pub type __int_least8_t = __int8_t;
pub type __uint_least8_t = __uint8_t;
pub type __int_least16_t = __int16_t;
pub type __uint_least16_t = __uint16_t;
pub type __int_least32_t = __int32_t;
pub type __uint_least32_t = __uint32_t;
pub type __int_least64_t = __int64_t;
pub type __uint_least64_t = __uint64_t;
pub type __quad_t = ::std::os::raw::c_long;
pub type __u_quad_t = ::std::os::raw::c_ulong;
pub type __intmax_t = ::std::os::raw::c_long;
pub type __uintmax_t = ::std::os::raw::c_ulong;
pub type __dev_t = ::std::os::raw::c_ulong;
pub type __uid_t = ::std::os::raw::c_uint;
pub type __gid_t = ::std::os::raw::c_uint;
pub type __ino_t = ::std::os::raw::c_ulong;
pub type __ino64_t = ::std::os::raw::c_ulong;
pub type __mode_t = ::std::os::raw::c_uint;
pub type __nlink_t = ::std::os::raw::c_uint;
pub type __off_t = ::std::os::raw::c_long;
pub type __off64_t = ::std::os::raw::c_long;
pub type __pid_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct __fsid_t {
    pub __val: [::std::os::raw::c_int; 2usize],
}
pub type __clock_t = ::std::os::raw::c_long;
pub type __rlim_t = ::std::os::raw::c_ulong;
pub type __rlim64_t = ::std::os::raw::c_ulong;
pub type __id_t = ::std::os::raw::c_uint;
pub type __time_t = ::std::os::raw::c_long;
pub type __useconds_t = ::std::os::raw::c_uint;
pub type __suseconds_t = ::std::os::raw::c_long;
pub type __suseconds64_t = ::std::os::raw::c_long;
pub type __daddr_t = ::std::os::raw::c_int;
pub type __key_t = ::std::os::raw::c_int;
pub type __clockid_t = ::std::os::raw::c_int;
pub type __timer_t = *mut ::std::os::raw::c_void;
pub type __blksize_t = ::std::os::raw::c_int;
pub type __blkcnt_t = ::std::os::raw::c_long;
pub type __blkcnt64_t = ::std::os::raw::c_long;
pub type __fsblkcnt_t = ::std::os::raw::c_ulong;
pub type __fsblkcnt64_t = ::std::os::raw::c_ulong;
pub type __fsfilcnt_t = ::std::os::raw::c_ulong;
pub type __fsfilcnt64_t = ::std::os::raw::c_ulong;
pub type __fsword_t = ::std::os::raw::c_long;
pub type __ssize_t = ::std::os::raw::c_long;
pub type __syscall_slong_t = ::std::os::raw::c_long;
pub type __syscall_ulong_t = ::std::os::raw::c_ulong;
pub type __loff_t = __off64_t;
pub type __caddr_t = *mut ::std::os::raw::c_char;
pub type __intptr_t = ::std::os::raw::c_long;
pub type __socklen_t = ::std::os::raw::c_uint;
pub type __sig_atomic_t = ::std::os::raw::c_int;
pub type int_least8_t = __int_least8_t;
pub type int_least16_t = __int_least16_t;
pub type int_least32_t = __int_least32_t;
pub type int_least64_t = __int_least64_t;
pub type uint_least8_t = __uint_least8_t;
pub type uint_least16_t = __uint_least16_t;
pub type uint_least32_t = __uint_least32_t;
pub type uint_least64_t = __uint_least64_t;
pub type int_fast8_t = ::std::os::raw::c_schar;
pub type int_fast16_t = ::std::os::raw::c_long;
pub type int_fast32_t = ::std::os::raw::c_long;
pub type int_fast64_t = ::std::os::raw::c_long;
pub type uint_fast8_t = ::std::os::raw::c_uchar;
pub type uint_fast16_t = ::std::os::raw::c_ulong;
pub type uint_fast32_t = ::std::os::raw::c_ulong;
pub type uint_fast64_t = ::std::os::raw::c_ulong;
pub type intmax_t = __intmax_t;
pub type uintmax_t = __uintmax_t;
pub type TableGenBool = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TableGen {
    _unused: [u8; 0],
}
pub type TableGenParserRef = *mut TableGen;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TableGenRecordKeeper {
    _unused: [u8; 0],
}
pub type TableGenRecordKeeperRef = *mut TableGenRecordKeeper;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TableGenRecordMap {
    _unused: [u8; 0],
}
pub type TableGenRecordMapRef = *mut TableGenRecordMap;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TableGenRecordMapIterator {
    _unused: [u8; 0],
}
pub type TableGenRecordKeeperIteratorRef = *mut TableGenRecordMapIterator;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TableGenRecordVector {
    _unused: [u8; 0],
}
pub type TableGenRecordVectorRef = *mut TableGenRecordVector;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TableGenRecordArray {
    _unused: [u8; 0],
}
pub type TableGenRecordArrayRef = *mut TableGenRecordArray;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TableGenRecord {
    _unused: [u8; 0],
}
pub type TableGenRecordRef = *mut TableGenRecord;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TableGenRecordVal {
    _unused: [u8; 0],
}
pub type TableGenRecordValRef = *mut TableGenRecordVal;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TableGenRecordValArray {
    _unused: [u8; 0],
}
pub type TableGenRecordValArrayRef = *mut TableGenRecordValArray;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TableGenTypedInit {
    _unused: [u8; 0],
}
pub type TableGenTypedInitRef = *mut TableGenTypedInit;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TableGenDagPair {
    _unused: [u8; 0],
}
pub type TableGenDagPairRef = *mut TableGenDagPair;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TableGenSourceLocation {
    _unused: [u8; 0],
}
pub type TableGenSourceLocationRef = *mut TableGenSourceLocation;
pub mod TableGenDiagKind {
    pub type Type = ::std::os::raw::c_uint;
    pub const TABLEGEN_DK_ERROR: Type = 0;
    pub const TABLEGEN_DK_WARNING: Type = 1;
    pub const TABLEGEN_DK_REMARK: Type = 2;
    pub const TABLEGEN_DK_NOTE: Type = 3;
}
pub mod TableGenRecTyKind {
    pub type Type = ::std::os::raw::c_uint;
    pub const TableGenBitRecTyKind: Type = 0;
    pub const TableGenBitsRecTyKind: Type = 1;
    pub const TableGenCodeRecTyKind: Type = 2;
    pub const TableGenIntRecTyKind: Type = 3;
    pub const TableGenStringRecTyKind: Type = 4;
    pub const TableGenListRecTyKind: Type = 5;
    pub const TableGenDagRecTyKind: Type = 6;
    pub const TableGenRecordRecTyKind: Type = 7;
    pub const TableGenInvalidRecTyKind: Type = 8;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TableGenStringRef {
    pub data: *const ::std::os::raw::c_char,
    pub len: usize,
}
impl Default for TableGenStringRef {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type TableGenStringCallback = ::std::option::Option<
    unsafe extern "C" fn(arg1: TableGenStringRef, arg2: *mut ::std::os::raw::c_void),
>;
unsafe extern "C" {
    pub fn tableGenGet() -> TableGenParserRef;
}
unsafe extern "C" {
    pub fn tableGenFree(tg_ref: TableGenParserRef);
}
unsafe extern "C" {
    pub fn tableGenAddSource(
        tg_ref: TableGenParserRef,
        source: *const ::std::os::raw::c_char,
    ) -> TableGenBool;
}
unsafe extern "C" {
    pub fn tableGenAddSourceFile(tg_ref: TableGenParserRef, source: TableGenStringRef);
}
unsafe extern "C" {
    pub fn tableGenAddIncludeDirectory(tg_ref: TableGenParserRef, include: TableGenStringRef);
}
unsafe extern "C" {
    #[doc = " NOTE: TableGen currently relies on global state within a given parser\n       invocation, so this function is not thread-safe."]
    pub fn tableGenParse(tg_ref: TableGenParserRef) -> TableGenRecordKeeperRef;
}
unsafe extern "C" {
    pub fn tableGenRecordKeeperFree(rk_ref: TableGenRecordKeeperRef);
}
unsafe extern "C" {
    pub fn tableGenRecordKeeperGetClasses(rk_ref: TableGenRecordKeeperRef) -> TableGenRecordMapRef;
}
unsafe extern "C" {
    pub fn tableGenRecordKeeperGetDefs(rk_ref: TableGenRecordKeeperRef) -> TableGenRecordMapRef;
}
unsafe extern "C" {
    pub fn tableGenRecordKeeperGetClass(
        rk_ref: TableGenRecordKeeperRef,
        name: TableGenStringRef,
    ) -> TableGenRecordRef;
}
unsafe extern "C" {
    pub fn tableGenRecordKeeperGetDef(
        rk_ref: TableGenRecordKeeperRef,
        name: TableGenStringRef,
    ) -> TableGenRecordRef;
}
unsafe extern "C" {
    pub fn tableGenRecordKeeperGetAllDerivedDefinitions(
        rk_ref: TableGenRecordKeeperRef,
        className: TableGenStringRef,
    ) -> TableGenRecordVectorRef;
}
unsafe extern "C" {
    pub fn tableGenRecordVectorGet(
        vec_ref: TableGenRecordVectorRef,
        index: usize,
    ) -> TableGenRecordRef;
}
unsafe extern "C" {
    pub fn tableGenRecordVectorFree(vec_ref: TableGenRecordVectorRef);
}
unsafe extern "C" {
    pub fn tableGenRecordKeeperGetFirstClass(
        rk_ref: TableGenRecordKeeperRef,
    ) -> TableGenRecordKeeperIteratorRef;
}
unsafe extern "C" {
    pub fn tableGenRecordKeeperGetFirstDef(
        rk_ref: TableGenRecordKeeperRef,
    ) -> TableGenRecordKeeperIteratorRef;
}
unsafe extern "C" {
    pub fn tableGenRecordKeeperGetNextClass(item: *mut TableGenRecordKeeperIteratorRef);
}
unsafe extern "C" {
    pub fn tableGenRecordKeeperGetNextDef(item: *mut TableGenRecordKeeperIteratorRef);
}
unsafe extern "C" {
    pub fn tableGenRecordKeeperItemGetName(
        item: TableGenRecordKeeperIteratorRef,
    ) -> TableGenStringRef;
}
unsafe extern "C" {
    pub fn tableGenRecordKeeperItemGetRecord(
        item: TableGenRecordKeeperIteratorRef,
    ) -> TableGenRecordRef;
}
unsafe extern "C" {
    pub fn tableGenRecordKeeperIteratorFree(item: TableGenRecordKeeperIteratorRef);
}
unsafe extern "C" {
    pub fn tableGenRecordKeeperIteratorClone(
        item: TableGenRecordKeeperIteratorRef,
    ) -> TableGenRecordKeeperIteratorRef;
}
unsafe extern "C" {
    pub fn tableGenRecordGetRecords(record_ref: TableGenRecordRef) -> TableGenRecordKeeperRef;
}
unsafe extern "C" {
    pub fn tableGenRecordGetName(record_ref: TableGenRecordRef) -> TableGenStringRef;
}
unsafe extern "C" {
    pub fn tableGenRecordGetValue(
        record_ref: TableGenRecordRef,
        name: TableGenStringRef,
    ) -> TableGenRecordValRef;
}
unsafe extern "C" {
    pub fn tableGenRecordGetFieldType(
        record_ref: TableGenRecordRef,
        name: TableGenStringRef,
    ) -> TableGenRecTyKind::Type;
}
unsafe extern "C" {
    pub fn tableGenRecordIsAnonymous(record_ref: TableGenRecordRef) -> TableGenBool;
}
unsafe extern "C" {
    pub fn tableGenRecordIsSubclassOf(
        record_ref: TableGenRecordRef,
        name: TableGenStringRef,
    ) -> TableGenBool;
}
unsafe extern "C" {
    pub fn tableGenRecordPrint(
        record_ref: TableGenRecordRef,
        callback: TableGenStringCallback,
        userData: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn tableGenRecordDump(record_ref: TableGenRecordRef);
}
unsafe extern "C" {
    pub fn tableGenRecordGetLoc(record_ref: TableGenRecordRef) -> TableGenSourceLocationRef;
}
unsafe extern "C" {
    pub fn tableGenRecordValGetName(rv_ref: TableGenRecordValRef) -> TableGenStringRef;
}
unsafe extern "C" {
    pub fn tableGenRecordValGetNameInit(rv_ref: TableGenRecordValRef) -> TableGenTypedInitRef;
}
unsafe extern "C" {
    pub fn tableGenRecordValGetType(rv_ref: TableGenRecordValRef) -> TableGenRecTyKind::Type;
}
unsafe extern "C" {
    pub fn tableGenRecordValGetValue(rv_ref: TableGenRecordValRef) -> TableGenTypedInitRef;
}
unsafe extern "C" {
    pub fn tableGenRecordValTest(rv_ref: TableGenRecordValRef);
}
unsafe extern "C" {
    pub fn tableGenRecordGetFirstValue(record_ref: TableGenRecordRef) -> TableGenRecordValRef;
}
unsafe extern "C" {
    pub fn tableGenRecordValNext(
        record: TableGenRecordRef,
        current: TableGenRecordValRef,
    ) -> TableGenRecordValRef;
}
unsafe extern "C" {
    pub fn tableGenRecordValPrint(
        rv_ref: TableGenRecordValRef,
        callback: TableGenStringCallback,
        userData: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn tableGenRecordValDump(rv_ref: TableGenRecordValRef);
}
unsafe extern "C" {
    pub fn tableGenRecordValGetLoc(rv_ref: TableGenRecordValRef) -> TableGenSourceLocationRef;
}
unsafe extern "C" {
    pub fn tableGenRecordValGetValAsNewString(
        rv_ref: TableGenRecordValRef,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn tableGenRecordValGetValAsBit(rv_ref: TableGenRecordValRef, bit: *mut i8)
    -> TableGenBool;
}
unsafe extern "C" {
    pub fn tableGenRecordValGetValAsBits(rv_ref: TableGenRecordValRef, len: *mut usize) -> *mut i8;
}
unsafe extern "C" {
    pub fn tableGenRecordValGetValAsInt(
        rv_ref: TableGenRecordValRef,
        integer: *mut i64,
    ) -> TableGenBool;
}
unsafe extern "C" {
    pub fn tableGenRecordValGetValAsRecord(rv_ref: TableGenRecordValRef) -> TableGenRecordRef;
}
unsafe extern "C" {
    pub fn tableGenRecordValGetValAsDefRecord(rv_ref: TableGenRecordValRef) -> TableGenRecordRef;
}
unsafe extern "C" {
    pub fn tableGenListRecordGetType(rv_ref: TableGenRecordValRef) -> TableGenRecTyKind::Type;
}
unsafe extern "C" {
    pub fn tableGenListRecordGet(
        rv_ref: TableGenTypedInitRef,
        index: usize,
    ) -> TableGenTypedInitRef;
}
unsafe extern "C" {
    pub fn tableGenListRecordNumElements(rv_ref: TableGenTypedInitRef) -> usize;
}
unsafe extern "C" {
    pub fn tableGenDagRecordOperator(rv_ref: TableGenTypedInitRef) -> TableGenRecordRef;
}
unsafe extern "C" {
    pub fn tableGenDagRecordGet(rv_ref: TableGenTypedInitRef, index: usize)
    -> TableGenTypedInitRef;
}
unsafe extern "C" {
    pub fn tableGenDagRecordArgName(
        rv_ref: TableGenTypedInitRef,
        index: usize,
    ) -> TableGenStringRef;
}
unsafe extern "C" {
    pub fn tableGenDagRecordNumArgs(rv_ref: TableGenTypedInitRef) -> usize;
}
unsafe extern "C" {
    pub fn tableGenInitRecType(ti: TableGenTypedInitRef) -> TableGenRecTyKind::Type;
}
unsafe extern "C" {
    pub fn tableGenBitInitGetValue(ti: TableGenTypedInitRef, bit: *mut i8) -> TableGenBool;
}
unsafe extern "C" {
    pub fn tableGenBitsInitGetValue(ti: TableGenTypedInitRef, len: *mut usize) -> *mut i8;
}
unsafe extern "C" {
    pub fn tableGenBitsInitGetNumBits(ti: TableGenTypedInitRef, len: *mut usize) -> TableGenBool;
}
unsafe extern "C" {
    pub fn tableGenBitsInitGetBitInit(
        ti: TableGenTypedInitRef,
        index: usize,
    ) -> TableGenTypedInitRef;
}
unsafe extern "C" {
    pub fn tableGenIntInitGetValue(ti: TableGenTypedInitRef, integer: *mut i64) -> TableGenBool;
}
unsafe extern "C" {
    pub fn tableGenStringInitGetValue(ti: TableGenTypedInitRef) -> TableGenStringRef;
}
unsafe extern "C" {
    pub fn tableGenStringInitGetValueNewString(
        ti: TableGenTypedInitRef,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn tableGenDefInitGetValue(ti: TableGenTypedInitRef) -> TableGenRecordRef;
}
unsafe extern "C" {
    pub fn tableGenInitPrint(
        ti: TableGenTypedInitRef,
        callback: TableGenStringCallback,
        userData: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn tableGenInitDump(ti: TableGenTypedInitRef);
}
unsafe extern "C" {
    pub fn tableGenPrintError(
        ref_: TableGenParserRef,
        loc_ref: TableGenSourceLocationRef,
        dk: TableGenDiagKind::Type,
        message: TableGenStringRef,
        callback: TableGenStringCallback,
        userData: *mut ::std::os::raw::c_void,
    ) -> TableGenBool;
}
unsafe extern "C" {
    pub fn tableGenSourceLocationNull() -> TableGenSourceLocationRef;
}
unsafe extern "C" {
    pub fn tableGenSourceLocationClone(
        loc_ref: TableGenSourceLocationRef,
    ) -> TableGenSourceLocationRef;
}
unsafe extern "C" {
    pub fn tableGenSourceLocationFree(loc_ref: TableGenSourceLocationRef);
}
unsafe extern "C" {
    pub fn tableGenBitArrayFree(bit_array: *mut i8);
}
unsafe extern "C" {
    pub fn tableGenStringFree(str_: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn tableGenStringArrayFree(str_array: *mut *const ::std::os::raw::c_char);
}
