/* automatically generated by rust-bindgen 0.72.1 */

pub const __WORDSIZE: u32 = 64;
pub const __has_safe_buffers: u32 = 1;
pub const __DARWIN_ONLY_64_BIT_INO_T: u32 = 1;
pub const __DARWIN_ONLY_UNIX_CONFORMANCE: u32 = 1;
pub const __DARWIN_ONLY_VERS_1050: u32 = 1;
pub const __DARWIN_UNIX03: u32 = 1;
pub const __DARWIN_64_BIT_INO_T: u32 = 1;
pub const __DARWIN_VERS_1050: u32 = 1;
pub const __DARWIN_NON_CANCELABLE: u32 = 0;
pub const __DARWIN_SUF_EXTSN: &[u8; 14] = b"$DARWIN_EXTSN\0";
pub const __DARWIN_C_ANSI: u32 = 4096;
pub const __DARWIN_C_FULL: u32 = 900000;
pub const __DARWIN_C_LEVEL: u32 = 900000;
pub const __STDC_WANT_LIB_EXT1__: u32 = 1;
pub const __DARWIN_NO_LONG_LONG: u32 = 0;
pub const _DARWIN_FEATURE_64_BIT_INODE: u32 = 1;
pub const _DARWIN_FEATURE_ONLY_64_BIT_INODE: u32 = 1;
pub const _DARWIN_FEATURE_ONLY_VERS_1050: u32 = 1;
pub const _DARWIN_FEATURE_ONLY_UNIX_CONFORMANCE: u32 = 1;
pub const _DARWIN_FEATURE_UNIX_CONFORMANCE: u32 = 3;
pub const __has_ptrcheck: u32 = 0;
pub const __has_bounds_safety_attributes: u32 = 0;
pub const USE_CLANG_TYPES: u32 = 0;
pub const __PTHREAD_SIZE__: u32 = 8176;
pub const __PTHREAD_ATTR_SIZE__: u32 = 56;
pub const __PTHREAD_MUTEXATTR_SIZE__: u32 = 8;
pub const __PTHREAD_MUTEX_SIZE__: u32 = 56;
pub const __PTHREAD_CONDATTR_SIZE__: u32 = 8;
pub const __PTHREAD_COND_SIZE__: u32 = 40;
pub const __PTHREAD_ONCE_SIZE__: u32 = 8;
pub const __PTHREAD_RWLOCK_SIZE__: u32 = 192;
pub const __PTHREAD_RWLOCKATTR_SIZE__: u32 = 16;
pub const INT8_MAX: u32 = 127;
pub const INT16_MAX: u32 = 32767;
pub const INT32_MAX: u32 = 2147483647;
pub const INT64_MAX: u64 = 9223372036854775807;
pub const INT8_MIN: i32 = -128;
pub const INT16_MIN: i32 = -32768;
pub const INT32_MIN: i32 = -2147483648;
pub const INT64_MIN: i64 = -9223372036854775808;
pub const UINT8_MAX: u32 = 255;
pub const UINT16_MAX: u32 = 65535;
pub const UINT32_MAX: u32 = 4294967295;
pub const UINT64_MAX: i32 = -1;
pub const INT_LEAST8_MIN: i32 = -128;
pub const INT_LEAST16_MIN: i32 = -32768;
pub const INT_LEAST32_MIN: i32 = -2147483648;
pub const INT_LEAST64_MIN: i64 = -9223372036854775808;
pub const INT_LEAST8_MAX: u32 = 127;
pub const INT_LEAST16_MAX: u32 = 32767;
pub const INT_LEAST32_MAX: u32 = 2147483647;
pub const INT_LEAST64_MAX: u64 = 9223372036854775807;
pub const UINT_LEAST8_MAX: u32 = 255;
pub const UINT_LEAST16_MAX: u32 = 65535;
pub const UINT_LEAST32_MAX: u32 = 4294967295;
pub const UINT_LEAST64_MAX: i32 = -1;
pub const INT_FAST8_MIN: i32 = -128;
pub const INT_FAST16_MIN: i32 = -32768;
pub const INT_FAST32_MIN: i32 = -2147483648;
pub const INT_FAST64_MIN: i64 = -9223372036854775808;
pub const INT_FAST8_MAX: u32 = 127;
pub const INT_FAST16_MAX: u32 = 32767;
pub const INT_FAST32_MAX: u32 = 2147483647;
pub const INT_FAST64_MAX: u64 = 9223372036854775807;
pub const UINT_FAST8_MAX: u32 = 255;
pub const UINT_FAST16_MAX: u32 = 65535;
pub const UINT_FAST32_MAX: u32 = 4294967295;
pub const UINT_FAST64_MAX: i32 = -1;
pub const INTPTR_MAX: u64 = 9223372036854775807;
pub const INTPTR_MIN: i64 = -9223372036854775808;
pub const UINTPTR_MAX: i32 = -1;
pub const SIZE_MAX: i32 = -1;
pub const RSIZE_MAX: i32 = -1;
pub const WINT_MIN: i32 = -2147483648;
pub const WINT_MAX: u32 = 2147483647;
pub const SIG_ATOMIC_MIN: i32 = -2147483648;
pub const SIG_ATOMIC_MAX: u32 = 2147483647;
pub type wchar_t = ::std::os::raw::c_int;
pub type max_align_t = f64;
pub type int_least8_t = i8;
pub type int_least16_t = i16;
pub type int_least32_t = i32;
pub type int_least64_t = i64;
pub type uint_least8_t = u8;
pub type uint_least16_t = u16;
pub type uint_least32_t = u32;
pub type uint_least64_t = u64;
pub type int_fast8_t = i8;
pub type int_fast16_t = i16;
pub type int_fast32_t = i32;
pub type int_fast64_t = i64;
pub type uint_fast8_t = u8;
pub type uint_fast16_t = u16;
pub type uint_fast32_t = u32;
pub type uint_fast64_t = u64;
pub type __int8_t = ::std::os::raw::c_schar;
pub type __uint8_t = ::std::os::raw::c_uchar;
pub type __int16_t = ::std::os::raw::c_short;
pub type __uint16_t = ::std::os::raw::c_ushort;
pub type __int32_t = ::std::os::raw::c_int;
pub type __uint32_t = ::std::os::raw::c_uint;
pub type __int64_t = ::std::os::raw::c_longlong;
pub type __uint64_t = ::std::os::raw::c_ulonglong;
pub type __darwin_intptr_t = ::std::os::raw::c_long;
pub type __darwin_natural_t = ::std::os::raw::c_uint;
pub type __darwin_ct_rune_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Copy, Clone)]
pub union __mbstate_t {
    pub __mbstate8: [::std::os::raw::c_char; 128usize],
    pub _mbstateL: ::std::os::raw::c_longlong,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __mbstate_t"][::std::mem::size_of::<__mbstate_t>() - 128usize];
    ["Alignment of __mbstate_t"][::std::mem::align_of::<__mbstate_t>() - 8usize];
    ["Offset of field: __mbstate_t::__mbstate8"]
        [::std::mem::offset_of!(__mbstate_t, __mbstate8) - 0usize];
    ["Offset of field: __mbstate_t::_mbstateL"]
        [::std::mem::offset_of!(__mbstate_t, _mbstateL) - 0usize];
};
pub type __darwin_mbstate_t = __mbstate_t;
pub type __darwin_ptrdiff_t = ::std::os::raw::c_long;
pub type __darwin_size_t = ::std::os::raw::c_ulong;
pub type __darwin_va_list = __builtin_va_list;
pub type __darwin_wchar_t = ::std::os::raw::c_int;
pub type __darwin_rune_t = __darwin_wchar_t;
pub type __darwin_wint_t = ::std::os::raw::c_int;
pub type __darwin_clock_t = ::std::os::raw::c_ulong;
pub type __darwin_socklen_t = __uint32_t;
pub type __darwin_ssize_t = ::std::os::raw::c_long;
pub type __darwin_time_t = ::std::os::raw::c_long;
pub type __darwin_blkcnt_t = __int64_t;
pub type __darwin_blksize_t = __int32_t;
pub type __darwin_dev_t = __int32_t;
pub type __darwin_fsblkcnt_t = ::std::os::raw::c_uint;
pub type __darwin_fsfilcnt_t = ::std::os::raw::c_uint;
pub type __darwin_gid_t = __uint32_t;
pub type __darwin_id_t = __uint32_t;
pub type __darwin_ino64_t = __uint64_t;
pub type __darwin_ino_t = __darwin_ino64_t;
pub type __darwin_mach_port_name_t = __darwin_natural_t;
pub type __darwin_mach_port_t = __darwin_mach_port_name_t;
pub type __darwin_mode_t = __uint16_t;
pub type __darwin_off_t = __int64_t;
pub type __darwin_pid_t = __int32_t;
pub type __darwin_sigset_t = __uint32_t;
pub type __darwin_suseconds_t = __int32_t;
pub type __darwin_uid_t = __uint32_t;
pub type __darwin_useconds_t = __uint32_t;
pub type __darwin_uuid_t = [::std::os::raw::c_uchar; 16usize];
pub type __darwin_uuid_string_t = [::std::os::raw::c_char; 37usize];
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __darwin_pthread_handler_rec {
    pub __routine: ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>,
    pub __arg: *mut ::std::os::raw::c_void,
    pub __next: *mut __darwin_pthread_handler_rec,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __darwin_pthread_handler_rec"]
        [::std::mem::size_of::<__darwin_pthread_handler_rec>() - 24usize];
    ["Alignment of __darwin_pthread_handler_rec"]
        [::std::mem::align_of::<__darwin_pthread_handler_rec>() - 8usize];
    ["Offset of field: __darwin_pthread_handler_rec::__routine"]
        [::std::mem::offset_of!(__darwin_pthread_handler_rec, __routine) - 0usize];
    ["Offset of field: __darwin_pthread_handler_rec::__arg"]
        [::std::mem::offset_of!(__darwin_pthread_handler_rec, __arg) - 8usize];
    ["Offset of field: __darwin_pthread_handler_rec::__next"]
        [::std::mem::offset_of!(__darwin_pthread_handler_rec, __next) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_attr_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 56usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_attr_t"][::std::mem::size_of::<_opaque_pthread_attr_t>() - 64usize];
    ["Alignment of _opaque_pthread_attr_t"]
        [::std::mem::align_of::<_opaque_pthread_attr_t>() - 8usize];
    ["Offset of field: _opaque_pthread_attr_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_attr_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_attr_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_attr_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_cond_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 40usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_cond_t"][::std::mem::size_of::<_opaque_pthread_cond_t>() - 48usize];
    ["Alignment of _opaque_pthread_cond_t"]
        [::std::mem::align_of::<_opaque_pthread_cond_t>() - 8usize];
    ["Offset of field: _opaque_pthread_cond_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_cond_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_cond_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_cond_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_condattr_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_condattr_t"]
        [::std::mem::size_of::<_opaque_pthread_condattr_t>() - 16usize];
    ["Alignment of _opaque_pthread_condattr_t"]
        [::std::mem::align_of::<_opaque_pthread_condattr_t>() - 8usize];
    ["Offset of field: _opaque_pthread_condattr_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_condattr_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_condattr_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_condattr_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_mutex_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 56usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_mutex_t"][::std::mem::size_of::<_opaque_pthread_mutex_t>() - 64usize];
    ["Alignment of _opaque_pthread_mutex_t"]
        [::std::mem::align_of::<_opaque_pthread_mutex_t>() - 8usize];
    ["Offset of field: _opaque_pthread_mutex_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_mutex_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_mutex_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_mutex_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_mutexattr_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_mutexattr_t"]
        [::std::mem::size_of::<_opaque_pthread_mutexattr_t>() - 16usize];
    ["Alignment of _opaque_pthread_mutexattr_t"]
        [::std::mem::align_of::<_opaque_pthread_mutexattr_t>() - 8usize];
    ["Offset of field: _opaque_pthread_mutexattr_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_mutexattr_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_mutexattr_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_mutexattr_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_once_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_once_t"][::std::mem::size_of::<_opaque_pthread_once_t>() - 16usize];
    ["Alignment of _opaque_pthread_once_t"]
        [::std::mem::align_of::<_opaque_pthread_once_t>() - 8usize];
    ["Offset of field: _opaque_pthread_once_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_once_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_once_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_once_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_rwlock_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 192usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_rwlock_t"]
        [::std::mem::size_of::<_opaque_pthread_rwlock_t>() - 200usize];
    ["Alignment of _opaque_pthread_rwlock_t"]
        [::std::mem::align_of::<_opaque_pthread_rwlock_t>() - 8usize];
    ["Offset of field: _opaque_pthread_rwlock_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_rwlock_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_rwlock_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_rwlock_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_rwlockattr_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 16usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_rwlockattr_t"]
        [::std::mem::size_of::<_opaque_pthread_rwlockattr_t>() - 24usize];
    ["Alignment of _opaque_pthread_rwlockattr_t"]
        [::std::mem::align_of::<_opaque_pthread_rwlockattr_t>() - 8usize];
    ["Offset of field: _opaque_pthread_rwlockattr_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_rwlockattr_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_rwlockattr_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_rwlockattr_t, __opaque) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_t {
    pub __sig: ::std::os::raw::c_long,
    pub __cleanup_stack: *mut __darwin_pthread_handler_rec,
    pub __opaque: [::std::os::raw::c_char; 8176usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _opaque_pthread_t"][::std::mem::size_of::<_opaque_pthread_t>() - 8192usize];
    ["Alignment of _opaque_pthread_t"][::std::mem::align_of::<_opaque_pthread_t>() - 8usize];
    ["Offset of field: _opaque_pthread_t::__sig"]
        [::std::mem::offset_of!(_opaque_pthread_t, __sig) - 0usize];
    ["Offset of field: _opaque_pthread_t::__cleanup_stack"]
        [::std::mem::offset_of!(_opaque_pthread_t, __cleanup_stack) - 8usize];
    ["Offset of field: _opaque_pthread_t::__opaque"]
        [::std::mem::offset_of!(_opaque_pthread_t, __opaque) - 16usize];
};
pub type __darwin_pthread_attr_t = _opaque_pthread_attr_t;
pub type __darwin_pthread_cond_t = _opaque_pthread_cond_t;
pub type __darwin_pthread_condattr_t = _opaque_pthread_condattr_t;
pub type __darwin_pthread_key_t = ::std::os::raw::c_ulong;
pub type __darwin_pthread_mutex_t = _opaque_pthread_mutex_t;
pub type __darwin_pthread_mutexattr_t = _opaque_pthread_mutexattr_t;
pub type __darwin_pthread_once_t = _opaque_pthread_once_t;
pub type __darwin_pthread_rwlock_t = _opaque_pthread_rwlock_t;
pub type __darwin_pthread_rwlockattr_t = _opaque_pthread_rwlockattr_t;
pub type __darwin_pthread_t = *mut _opaque_pthread_t;
pub type intmax_t = ::std::os::raw::c_long;
pub type uintmax_t = ::std::os::raw::c_ulong;
pub type TableGenBool = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TableGen {
    _unused: [u8; 0],
}
pub type TableGenParserRef = *mut TableGen;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TableGenRecordKeeper {
    _unused: [u8; 0],
}
pub type TableGenRecordKeeperRef = *mut TableGenRecordKeeper;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TableGenRecordMap {
    _unused: [u8; 0],
}
pub type TableGenRecordMapRef = *mut TableGenRecordMap;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TableGenRecordMapIterator {
    _unused: [u8; 0],
}
pub type TableGenRecordKeeperIteratorRef = *mut TableGenRecordMapIterator;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TableGenRecordVector {
    _unused: [u8; 0],
}
pub type TableGenRecordVectorRef = *mut TableGenRecordVector;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TableGenRecordArray {
    _unused: [u8; 0],
}
pub type TableGenRecordArrayRef = *mut TableGenRecordArray;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TableGenRecord {
    _unused: [u8; 0],
}
pub type TableGenRecordRef = *mut TableGenRecord;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TableGenRecordVal {
    _unused: [u8; 0],
}
pub type TableGenRecordValRef = *mut TableGenRecordVal;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TableGenRecordValArray {
    _unused: [u8; 0],
}
pub type TableGenRecordValArrayRef = *mut TableGenRecordValArray;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TableGenTypedInit {
    _unused: [u8; 0],
}
pub type TableGenTypedInitRef = *mut TableGenTypedInit;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TableGenDagPair {
    _unused: [u8; 0],
}
pub type TableGenDagPairRef = *mut TableGenDagPair;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TableGenSourceLocation {
    _unused: [u8; 0],
}
pub type TableGenSourceLocationRef = *mut TableGenSourceLocation;
pub mod TableGenDiagKind {
    pub type Type = ::std::os::raw::c_uint;
    pub const TABLEGEN_DK_ERROR: Type = 0;
    pub const TABLEGEN_DK_WARNING: Type = 1;
    pub const TABLEGEN_DK_REMARK: Type = 2;
    pub const TABLEGEN_DK_NOTE: Type = 3;
}
pub mod TableGenRecTyKind {
    pub type Type = ::std::os::raw::c_uint;
    pub const TableGenBitRecTyKind: Type = 0;
    pub const TableGenBitsRecTyKind: Type = 1;
    pub const TableGenCodeRecTyKind: Type = 2;
    pub const TableGenIntRecTyKind: Type = 3;
    pub const TableGenStringRecTyKind: Type = 4;
    pub const TableGenListRecTyKind: Type = 5;
    pub const TableGenDagRecTyKind: Type = 6;
    pub const TableGenRecordRecTyKind: Type = 7;
    pub const TableGenInvalidRecTyKind: Type = 8;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TableGenStringRef {
    pub data: *const ::std::os::raw::c_char,
    pub len: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of TableGenStringRef"][::std::mem::size_of::<TableGenStringRef>() - 16usize];
    ["Alignment of TableGenStringRef"][::std::mem::align_of::<TableGenStringRef>() - 8usize];
    ["Offset of field: TableGenStringRef::data"]
        [::std::mem::offset_of!(TableGenStringRef, data) - 0usize];
    ["Offset of field: TableGenStringRef::len"]
        [::std::mem::offset_of!(TableGenStringRef, len) - 8usize];
};
pub type TableGenStringCallback = ::std::option::Option<
    unsafe extern "C" fn(arg1: TableGenStringRef, arg2: *mut ::std::os::raw::c_void),
>;
unsafe extern "C" {
    pub fn tableGenGet() -> TableGenParserRef;
}
unsafe extern "C" {
    pub fn tableGenFree(tg_ref: TableGenParserRef);
}
unsafe extern "C" {
    pub fn tableGenAddSource(
        tg_ref: TableGenParserRef,
        source: *const ::std::os::raw::c_char,
    ) -> TableGenBool;
}
unsafe extern "C" {
    pub fn tableGenAddSourceFile(tg_ref: TableGenParserRef, source: TableGenStringRef);
}
unsafe extern "C" {
    pub fn tableGenAddIncludeDirectory(tg_ref: TableGenParserRef, include: TableGenStringRef);
}
unsafe extern "C" {
    #[doc = " NOTE: TableGen currently relies on global state within a given parser\n       invocation, so this function is not thread-safe."]
    pub fn tableGenParse(tg_ref: TableGenParserRef) -> TableGenRecordKeeperRef;
}
unsafe extern "C" {
    pub fn tableGenRecordKeeperFree(rk_ref: TableGenRecordKeeperRef);
}
unsafe extern "C" {
    pub fn tableGenRecordKeeperGetClasses(rk_ref: TableGenRecordKeeperRef) -> TableGenRecordMapRef;
}
unsafe extern "C" {
    pub fn tableGenRecordKeeperGetDefs(rk_ref: TableGenRecordKeeperRef) -> TableGenRecordMapRef;
}
unsafe extern "C" {
    pub fn tableGenRecordKeeperGetClass(
        rk_ref: TableGenRecordKeeperRef,
        name: TableGenStringRef,
    ) -> TableGenRecordRef;
}
unsafe extern "C" {
    pub fn tableGenRecordKeeperGetDef(
        rk_ref: TableGenRecordKeeperRef,
        name: TableGenStringRef,
    ) -> TableGenRecordRef;
}
unsafe extern "C" {
    pub fn tableGenRecordKeeperGetAllDerivedDefinitions(
        rk_ref: TableGenRecordKeeperRef,
        className: TableGenStringRef,
    ) -> TableGenRecordVectorRef;
}
unsafe extern "C" {
    pub fn tableGenRecordVectorGet(
        vec_ref: TableGenRecordVectorRef,
        index: usize,
    ) -> TableGenRecordRef;
}
unsafe extern "C" {
    pub fn tableGenRecordVectorFree(vec_ref: TableGenRecordVectorRef);
}
unsafe extern "C" {
    pub fn tableGenRecordKeeperGetFirstClass(
        rk_ref: TableGenRecordKeeperRef,
    ) -> TableGenRecordKeeperIteratorRef;
}
unsafe extern "C" {
    pub fn tableGenRecordKeeperGetFirstDef(
        rk_ref: TableGenRecordKeeperRef,
    ) -> TableGenRecordKeeperIteratorRef;
}
unsafe extern "C" {
    pub fn tableGenRecordKeeperGetNextClass(item: *mut TableGenRecordKeeperIteratorRef);
}
unsafe extern "C" {
    pub fn tableGenRecordKeeperGetNextDef(item: *mut TableGenRecordKeeperIteratorRef);
}
unsafe extern "C" {
    pub fn tableGenRecordKeeperItemGetName(
        item: TableGenRecordKeeperIteratorRef,
    ) -> TableGenStringRef;
}
unsafe extern "C" {
    pub fn tableGenRecordKeeperItemGetRecord(
        item: TableGenRecordKeeperIteratorRef,
    ) -> TableGenRecordRef;
}
unsafe extern "C" {
    pub fn tableGenRecordKeeperIteratorFree(item: TableGenRecordKeeperIteratorRef);
}
unsafe extern "C" {
    pub fn tableGenRecordKeeperIteratorClone(
        item: TableGenRecordKeeperIteratorRef,
    ) -> TableGenRecordKeeperIteratorRef;
}
unsafe extern "C" {
    pub fn tableGenRecordGetRecords(record_ref: TableGenRecordRef) -> TableGenRecordKeeperRef;
}
unsafe extern "C" {
    pub fn tableGenRecordGetName(record_ref: TableGenRecordRef) -> TableGenStringRef;
}
unsafe extern "C" {
    pub fn tableGenRecordGetValue(
        record_ref: TableGenRecordRef,
        name: TableGenStringRef,
    ) -> TableGenRecordValRef;
}
unsafe extern "C" {
    pub fn tableGenRecordGetFieldType(
        record_ref: TableGenRecordRef,
        name: TableGenStringRef,
    ) -> TableGenRecTyKind::Type;
}
unsafe extern "C" {
    pub fn tableGenRecordIsAnonymous(record_ref: TableGenRecordRef) -> TableGenBool;
}
unsafe extern "C" {
    pub fn tableGenRecordIsSubclassOf(
        record_ref: TableGenRecordRef,
        name: TableGenStringRef,
    ) -> TableGenBool;
}
unsafe extern "C" {
    pub fn tableGenRecordPrint(
        record_ref: TableGenRecordRef,
        callback: TableGenStringCallback,
        userData: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn tableGenRecordDump(record_ref: TableGenRecordRef);
}
unsafe extern "C" {
    pub fn tableGenRecordGetLoc(record_ref: TableGenRecordRef) -> TableGenSourceLocationRef;
}
unsafe extern "C" {
    pub fn tableGenRecordValGetName(rv_ref: TableGenRecordValRef) -> TableGenStringRef;
}
unsafe extern "C" {
    pub fn tableGenRecordValGetNameInit(rv_ref: TableGenRecordValRef) -> TableGenTypedInitRef;
}
unsafe extern "C" {
    pub fn tableGenRecordValGetType(rv_ref: TableGenRecordValRef) -> TableGenRecTyKind::Type;
}
unsafe extern "C" {
    pub fn tableGenRecordValGetValue(rv_ref: TableGenRecordValRef) -> TableGenTypedInitRef;
}
unsafe extern "C" {
    pub fn tableGenRecordValTest(rv_ref: TableGenRecordValRef);
}
unsafe extern "C" {
    pub fn tableGenRecordGetFirstValue(record_ref: TableGenRecordRef) -> TableGenRecordValRef;
}
unsafe extern "C" {
    pub fn tableGenRecordValNext(
        record: TableGenRecordRef,
        current: TableGenRecordValRef,
    ) -> TableGenRecordValRef;
}
unsafe extern "C" {
    pub fn tableGenRecordValPrint(
        rv_ref: TableGenRecordValRef,
        callback: TableGenStringCallback,
        userData: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn tableGenRecordValDump(rv_ref: TableGenRecordValRef);
}
unsafe extern "C" {
    pub fn tableGenRecordValGetLoc(rv_ref: TableGenRecordValRef) -> TableGenSourceLocationRef;
}
unsafe extern "C" {
    pub fn tableGenRecordValGetValAsNewString(
        rv_ref: TableGenRecordValRef,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn tableGenRecordValGetValAsBit(rv_ref: TableGenRecordValRef, bit: *mut i8)
        -> TableGenBool;
}
unsafe extern "C" {
    pub fn tableGenRecordValGetValAsBits(rv_ref: TableGenRecordValRef, len: *mut usize) -> *mut i8;
}
unsafe extern "C" {
    pub fn tableGenRecordValGetValAsInt(
        rv_ref: TableGenRecordValRef,
        integer: *mut i64,
    ) -> TableGenBool;
}
unsafe extern "C" {
    pub fn tableGenRecordValGetValAsRecord(rv_ref: TableGenRecordValRef) -> TableGenRecordRef;
}
unsafe extern "C" {
    pub fn tableGenRecordValGetValAsDefRecord(rv_ref: TableGenRecordValRef) -> TableGenRecordRef;
}
unsafe extern "C" {
    pub fn tableGenListRecordGetType(rv_ref: TableGenRecordValRef) -> TableGenRecTyKind::Type;
}
unsafe extern "C" {
    pub fn tableGenListRecordGet(
        rv_ref: TableGenTypedInitRef,
        index: usize,
    ) -> TableGenTypedInitRef;
}
unsafe extern "C" {
    pub fn tableGenListRecordNumElements(rv_ref: TableGenTypedInitRef) -> usize;
}
unsafe extern "C" {
    pub fn tableGenDagRecordOperator(rv_ref: TableGenTypedInitRef) -> TableGenRecordRef;
}
unsafe extern "C" {
    pub fn tableGenDagRecordGet(rv_ref: TableGenTypedInitRef, index: usize)
        -> TableGenTypedInitRef;
}
unsafe extern "C" {
    pub fn tableGenDagRecordArgName(
        rv_ref: TableGenTypedInitRef,
        index: usize,
    ) -> TableGenStringRef;
}
unsafe extern "C" {
    pub fn tableGenDagRecordNumArgs(rv_ref: TableGenTypedInitRef) -> usize;
}
unsafe extern "C" {
    pub fn tableGenInitRecType(ti: TableGenTypedInitRef) -> TableGenRecTyKind::Type;
}
unsafe extern "C" {
    pub fn tableGenBitInitGetValue(ti: TableGenTypedInitRef, bit: *mut i8) -> TableGenBool;
}
unsafe extern "C" {
    pub fn tableGenBitsInitGetValue(ti: TableGenTypedInitRef, len: *mut usize) -> *mut i8;
}
unsafe extern "C" {
    pub fn tableGenBitsInitGetNumBits(ti: TableGenTypedInitRef, len: *mut usize) -> TableGenBool;
}
unsafe extern "C" {
    pub fn tableGenBitsInitGetBitInit(
        ti: TableGenTypedInitRef,
        index: usize,
    ) -> TableGenTypedInitRef;
}
unsafe extern "C" {
    pub fn tableGenIntInitGetValue(ti: TableGenTypedInitRef, integer: *mut i64) -> TableGenBool;
}
unsafe extern "C" {
    pub fn tableGenStringInitGetValue(ti: TableGenTypedInitRef) -> TableGenStringRef;
}
unsafe extern "C" {
    pub fn tableGenStringInitGetValueNewString(
        ti: TableGenTypedInitRef,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn tableGenDefInitGetValue(ti: TableGenTypedInitRef) -> TableGenRecordRef;
}
unsafe extern "C" {
    pub fn tableGenInitPrint(
        ti: TableGenTypedInitRef,
        callback: TableGenStringCallback,
        userData: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn tableGenInitDump(ti: TableGenTypedInitRef);
}
unsafe extern "C" {
    pub fn tableGenPrintError(
        ref_: TableGenParserRef,
        loc_ref: TableGenSourceLocationRef,
        dk: TableGenDiagKind::Type,
        message: TableGenStringRef,
        callback: TableGenStringCallback,
        userData: *mut ::std::os::raw::c_void,
    ) -> TableGenBool;
}
unsafe extern "C" {
    pub fn tableGenSourceLocationNull() -> TableGenSourceLocationRef;
}
unsafe extern "C" {
    pub fn tableGenSourceLocationClone(
        loc_ref: TableGenSourceLocationRef,
    ) -> TableGenSourceLocationRef;
}
unsafe extern "C" {
    pub fn tableGenSourceLocationFree(loc_ref: TableGenSourceLocationRef);
}
unsafe extern "C" {
    pub fn tableGenBitArrayFree(bit_array: *mut i8);
}
unsafe extern "C" {
    pub fn tableGenStringFree(str_: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn tableGenStringArrayFree(str_array: *mut *const ::std::os::raw::c_char);
}
pub type __builtin_va_list = *mut ::std::os::raw::c_char;
