/* automatically generated by rust-bindgen 0.72.1 */

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]

pub const _STL_COMPILER_PREPROCESSOR: u32 = 1;
pub const _VCRT_COMPILER_PREPROCESSOR: u32 = 1;
pub const _SAL_VERSION: u32 = 20;
pub const __SAL_H_VERSION: u32 = 180000000;
pub const _USE_DECLSPECS_FOR_SAL: u32 = 0;
pub const _USE_ATTRIBUTES_FOR_SAL: u32 = 0;
pub const _CRT_PACKING: u32 = 8;
pub const _HAS_EXCEPTIONS: u32 = 1;
pub const NULL: u32 = 0;
pub const _HAS_CXX17: u32 = 1;
pub const _HAS_CXX20: u32 = 0;
pub const _HAS_CXX23: u32 = 0;
pub const _HAS_CXX26: u32 = 0;
pub const _HAS_NODISCARD: u32 = 1;
pub const _STL_WARNING_LEVEL: u32 = 3;
pub const _STL_DISABLED_WARNING_C5053: u32 = 5053;
pub const _CPPLIB_VER: u32 = 650;
pub const _MSVC_STL_VERSION: u32 = 143;
pub const _MSVC_STL_UPDATE: u32 = 202503;
pub const _HAS_STATIC_RTTI: u32 = 1;
pub const _HAS_STD_BYTE: u32 = 1;
pub const _ENFORCE_MATCHING_ALLOCATORS: u32 = 1;
pub const _ENFORCE_FACET_SPECIALIZATIONS: u32 = 0;
pub const _FACET_SPECIALIZATION_MESSAGE : & [u8 ; 167] = b"Unsupported facet specialization; see N4950 [locale.category]. Either use a Standard specialization or define _ENFORCE_FACET_SPECIALIZATIONS=0 to suppress this error.\0" ;
pub const _STL_OPTIMIZE_SYSTEM_ERROR_OPERATORS: u32 = 1;
pub const _STD_VECTORIZE_WITH_FLOAT_CONTROL: u32 = 1;
pub const __cpp_lib_chrono_udls: u32 = 201304;
pub const __cpp_lib_complex_udls: u32 = 201309;
pub const __cpp_lib_exchange_function: u32 = 201304;
pub const __cpp_lib_freestanding_algorithm: u32 = 202311;
pub const __cpp_lib_freestanding_array: u32 = 202311;
pub const __cpp_lib_freestanding_char_traits: u32 = 202306;
pub const __cpp_lib_freestanding_cstdlib: u32 = 202306;
pub const __cpp_lib_freestanding_cstring: u32 = 202311;
pub const __cpp_lib_freestanding_cwchar: u32 = 202306;
pub const __cpp_lib_freestanding_errc: u32 = 202306;
pub const __cpp_lib_freestanding_feature_test_macros: u32 = 202306;
pub const __cpp_lib_freestanding_functional: u32 = 202306;
pub const __cpp_lib_freestanding_iterator: u32 = 202306;
pub const __cpp_lib_freestanding_memory: u32 = 202306;
pub const __cpp_lib_freestanding_operator_new: u32 = 202306;
pub const __cpp_lib_freestanding_ratio: u32 = 202306;
pub const __cpp_lib_freestanding_tuple: u32 = 202306;
pub const __cpp_lib_freestanding_utility: u32 = 202306;
pub const __cpp_lib_generic_associative_lookup: u32 = 201304;
pub const __cpp_lib_integer_sequence: u32 = 201304;
pub const __cpp_lib_integral_constant_callable: u32 = 201304;
pub const __cpp_lib_is_final: u32 = 201402;
pub const __cpp_lib_is_null_pointer: u32 = 201309;
pub const __cpp_lib_make_reverse_iterator: u32 = 201402;
pub const __cpp_lib_make_unique: u32 = 201304;
pub const __cpp_lib_null_iterators: u32 = 201304;
pub const __cpp_lib_quoted_string_io: u32 = 201304;
pub const __cpp_lib_result_of_sfinae: u32 = 201210;
pub const __cpp_lib_robust_nonmodifying_seq_ops: u32 = 201304;
pub const __cpp_lib_shared_timed_mutex: u32 = 201402;
pub const __cpp_lib_string_udls: u32 = 201304;
pub const __cpp_lib_transformation_trait_aliases: u32 = 201304;
pub const __cpp_lib_tuple_element_t: u32 = 201402;
pub const __cpp_lib_tuples_by_type: u32 = 201304;
pub const __cpp_lib_addressof_constexpr: u32 = 201603;
pub const __cpp_lib_allocator_traits_is_always_equal: u32 = 201411;
pub const __cpp_lib_as_const: u32 = 201510;
pub const __cpp_lib_bool_constant: u32 = 201505;
pub const __cpp_lib_enable_shared_from_this: u32 = 201603;
pub const __cpp_lib_incomplete_container_elements: u32 = 201505;
pub const __cpp_lib_invoke: u32 = 201411;
pub const __cpp_lib_logical_traits: u32 = 201510;
pub const __cpp_lib_map_try_emplace: u32 = 201411;
pub const __cpp_lib_nonmember_container_access: u32 = 201411;
pub const __cpp_lib_shared_mutex: u32 = 201505;
pub const __cpp_lib_transparent_operators: u32 = 201510;
pub const __cpp_lib_type_trait_variable_templates: u32 = 201510;
pub const __cpp_lib_uncaught_exceptions: u32 = 201411;
pub const __cpp_lib_unordered_map_try_emplace: u32 = 201411;
pub const __cpp_lib_void_t: u32 = 201411;
pub const __cpp_lib_any: u32 = 201606;
pub const __cpp_lib_apply: u32 = 201603;
pub const __cpp_lib_atomic_is_always_lock_free: u32 = 201603;
pub const __cpp_lib_boyer_moore_searcher: u32 = 201603;
pub const __cpp_lib_byte: u32 = 201603;
pub const __cpp_lib_clamp: u32 = 201603;
pub const __cpp_lib_filesystem: u32 = 201703;
pub const __cpp_lib_freestanding_charconv: u32 = 202306;
pub const __cpp_lib_freestanding_optional: u32 = 202311;
pub const __cpp_lib_freestanding_string_view: u32 = 202311;
pub const __cpp_lib_freestanding_variant: u32 = 202311;
pub const __cpp_lib_gcd_lcm: u32 = 201606;
pub const __cpp_lib_hardware_interference_size: u32 = 201703;
pub const __cpp_lib_has_unique_object_representations: u32 = 201606;
pub const __cpp_lib_hypot: u32 = 201603;
pub const __cpp_lib_is_aggregate: u32 = 201703;
pub const __cpp_lib_is_invocable: u32 = 201703;
pub const __cpp_lib_is_swappable: u32 = 201603;
pub const __cpp_lib_launder: u32 = 201606;
pub const __cpp_lib_make_from_tuple: u32 = 201606;
pub const __cpp_lib_math_special_functions: u32 = 201603;
pub const __cpp_lib_memory_resource: u32 = 201603;
pub const __cpp_lib_node_extract: u32 = 201606;
pub const __cpp_lib_not_fn: u32 = 201603;
pub const __cpp_lib_parallel_algorithm: u32 = 201603;
pub const __cpp_lib_raw_memory_algorithms: u32 = 201606;
pub const __cpp_lib_sample: u32 = 201603;
pub const __cpp_lib_scoped_lock: u32 = 201703;
pub const __cpp_lib_shared_ptr_weak_type: u32 = 201606;
pub const __cpp_lib_string_view: u32 = 201803;
pub const __cpp_lib_to_chars: u32 = 201611;
pub const __cpp_lib_atomic_value_initialization: u32 = 201911;
pub const __cpp_lib_array_constexpr: u32 = 201803;
pub const __cpp_lib_chrono: u32 = 201611;
pub const __cpp_lib_execution: u32 = 201603;
pub const __cpp_lib_optional: u32 = 201606;
pub const __cpp_lib_shared_ptr_arrays: u32 = 201611;
pub const __cpp_lib_variant: u32 = 202102;
pub const __cpp_lib_experimental_filesystem: u32 = 201406;
pub const _USE_EXTERN_CXX_EVERYWHERE_FOR_STL: u32 = 0;
pub const _STL_WIN32_WINNT_VISTA: u32 = 1536;
pub const _STL_WIN32_WINNT_WIN7: u32 = 1537;
pub const _STL_WIN32_WINNT_WIN8: u32 = 1538;
pub const _STL_WIN32_WINNT_WIN10: u32 = 2560;
pub const _STL_WIN32_WINNT: u32 = 1537;
pub const WCHAR_MIN: u32 = 0;
pub const WCHAR_MAX: u32 = 65535;
pub const WINT_MIN: u32 = 0;
pub const WINT_MAX: u32 = 65535;
pub type va_list = *mut ::std::os::raw::c_char;
unsafe extern "C" {
    pub fn __va_start(arg1: *mut va_list, ...);
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct __vcrt_va_list_is_reference {
    pub _address: u8,
}
pub mod __vcrt_va_list_is_reference__bindgen_ty_1 {
    pub type Type = bool;
    pub const __the_value: Type = false;
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct __vcrt_assert_va_start_is_not_reference {
    pub _address: u8,
}
pub type __vcrt_bool = bool;
unsafe extern "C" {
    pub fn __security_init_cookie();
}
unsafe extern "C" {
    pub fn __security_check_cookie(_StackCookie: usize);
}
unsafe extern "C" {
    pub fn __report_gsfailure(_StackCookie: usize) -> !;
}
unsafe extern "C" {
    pub static mut __security_cookie: usize;
}
pub type std_nullptr_t = *const ::std::os::raw::c_void;
pub type std_integral_constant_value_type<_Ty> = _Ty;
pub type std_integral_constant_type = u8;
pub type std_bool_constant = u8;
pub type std_true_type = u8;
pub type std_false_type = u8;
pub type std_enable_if_t = u8;
pub type std_conditional_type<_Ty1> = _Ty1;
pub type std_conditional_t = u8;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct std_is_same {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct std_remove_const {
    pub _address: u8,
}
pub type std_remove_const_type<_Ty> = _Ty;
pub type std_remove_const_t = std_remove_const;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct std_remove_volatile {
    pub _address: u8,
}
pub type std_remove_volatile_type<_Ty> = _Ty;
pub type std_remove_volatile_t = std_remove_volatile;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct std_remove_cv {
    pub _address: u8,
}
pub type std_remove_cv_type<_Ty> = _Ty;
pub type std_remove_cv__Apply = u8;
pub type std_remove_cv_t = std_remove_cv;
pub type std__Disjunction_type<_First> = _First;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct std_disjunction {
    pub _base: std_false_type,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct std_is_integral {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct std_is_floating_point {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct std_is_arithmetic {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct std_remove_reference {
    pub _address: u8,
}
pub type std_remove_reference_type<_Ty> = _Ty;
pub type std_remove_reference__Const_thru_ref_type<_Ty> = _Ty;
pub type std_remove_reference_t = std_remove_reference;
pub type std__Const_thru_ref = std_remove_reference;
pub type std__Remove_cvref_t = std_remove_cv_t;
pub type std_max_align_t = f64;
pub mod std_byte {
    pub type Type = ::std::os::raw::c_uchar;
}
pub type max_align_t = f64;
pub type int_least8_t = ::std::os::raw::c_schar;
pub type int_least16_t = ::std::os::raw::c_short;
pub type int_least32_t = ::std::os::raw::c_int;
pub type int_least64_t = ::std::os::raw::c_longlong;
pub type uint_least8_t = ::std::os::raw::c_uchar;
pub type uint_least16_t = ::std::os::raw::c_ushort;
pub type uint_least32_t = ::std::os::raw::c_uint;
pub type uint_least64_t = ::std::os::raw::c_ulonglong;
pub type int_fast8_t = ::std::os::raw::c_schar;
pub type int_fast16_t = ::std::os::raw::c_int;
pub type int_fast32_t = ::std::os::raw::c_int;
pub type int_fast64_t = ::std::os::raw::c_longlong;
pub type uint_fast8_t = ::std::os::raw::c_uchar;
pub type uint_fast16_t = ::std::os::raw::c_uint;
pub type uint_fast32_t = ::std::os::raw::c_uint;
pub type uint_fast64_t = ::std::os::raw::c_ulonglong;
pub type intmax_t = ::std::os::raw::c_longlong;
pub type uintmax_t = ::std::os::raw::c_ulonglong;
pub type TableGenBool = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TableGen {
    _unused: [u8; 0],
}
pub type TableGenParserRef = *mut TableGen;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TableGenRecordKeeper {
    _unused: [u8; 0],
}
pub type TableGenRecordKeeperRef = *mut TableGenRecordKeeper;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TableGenRecordMap {
    _unused: [u8; 0],
}
pub type TableGenRecordMapRef = *mut TableGenRecordMap;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TableGenRecordMapIterator {
    _unused: [u8; 0],
}
pub type TableGenRecordKeeperIteratorRef = *mut TableGenRecordMapIterator;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TableGenRecordVector {
    _unused: [u8; 0],
}
pub type TableGenRecordVectorRef = *mut TableGenRecordVector;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TableGenRecordArray {
    _unused: [u8; 0],
}
pub type TableGenRecordArrayRef = *mut TableGenRecordArray;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TableGenRecord {
    _unused: [u8; 0],
}
pub type TableGenRecordRef = *mut TableGenRecord;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TableGenRecordVal {
    _unused: [u8; 0],
}
pub type TableGenRecordValRef = *mut TableGenRecordVal;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TableGenRecordValArray {
    _unused: [u8; 0],
}
pub type TableGenRecordValArrayRef = *mut TableGenRecordValArray;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TableGenTypedInit {
    _unused: [u8; 0],
}
pub type TableGenTypedInitRef = *mut TableGenTypedInit;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TableGenDagPair {
    _unused: [u8; 0],
}
pub type TableGenDagPairRef = *mut TableGenDagPair;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TableGenSourceLocation {
    _unused: [u8; 0],
}
pub type TableGenSourceLocationRef = *mut TableGenSourceLocation;
pub mod TableGenDiagKind {
    pub type Type = ::std::os::raw::c_int;
    pub const TABLEGEN_DK_ERROR: Type = 0;
    pub const TABLEGEN_DK_WARNING: Type = 1;
    pub const TABLEGEN_DK_REMARK: Type = 2;
    pub const TABLEGEN_DK_NOTE: Type = 3;
}
pub mod TableGenRecTyKind {
    pub type Type = ::std::os::raw::c_int;
    pub const TableGenBitRecTyKind: Type = 0;
    pub const TableGenBitsRecTyKind: Type = 1;
    pub const TableGenCodeRecTyKind: Type = 2;
    pub const TableGenIntRecTyKind: Type = 3;
    pub const TableGenStringRecTyKind: Type = 4;
    pub const TableGenListRecTyKind: Type = 5;
    pub const TableGenDagRecTyKind: Type = 6;
    pub const TableGenRecordRecTyKind: Type = 7;
    pub const TableGenInvalidRecTyKind: Type = 8;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TableGenStringRef {
    pub data: *const ::std::os::raw::c_char,
    pub len: usize,
}
impl Default for TableGenStringRef {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type TableGenStringCallback = ::std::option::Option<
    unsafe extern "C" fn(arg1: TableGenStringRef, arg2: *mut ::std::os::raw::c_void),
>;
unsafe extern "C" {
    pub fn tableGenGet() -> TableGenParserRef;
}
unsafe extern "C" {
    pub fn tableGenFree(tg_ref: TableGenParserRef);
}
unsafe extern "C" {
    pub fn tableGenAddSource(
        tg_ref: TableGenParserRef,
        source: *const ::std::os::raw::c_char,
    ) -> TableGenBool;
}
unsafe extern "C" {
    pub fn tableGenAddSourceFile(tg_ref: TableGenParserRef, source: TableGenStringRef);
}
unsafe extern "C" {
    pub fn tableGenAddIncludeDirectory(tg_ref: TableGenParserRef, include: TableGenStringRef);
}
unsafe extern "C" {
    #[doc = " NOTE: TableGen currently relies on global state within a given parser\n       invocation, so this function is not thread-safe."]
    pub fn tableGenParse(tg_ref: TableGenParserRef) -> TableGenRecordKeeperRef;
}
unsafe extern "C" {
    pub fn tableGenRecordKeeperFree(rk_ref: TableGenRecordKeeperRef);
}
unsafe extern "C" {
    pub fn tableGenRecordKeeperGetClasses(rk_ref: TableGenRecordKeeperRef) -> TableGenRecordMapRef;
}
unsafe extern "C" {
    pub fn tableGenRecordKeeperGetDefs(rk_ref: TableGenRecordKeeperRef) -> TableGenRecordMapRef;
}
unsafe extern "C" {
    pub fn tableGenRecordKeeperGetClass(
        rk_ref: TableGenRecordKeeperRef,
        name: TableGenStringRef,
    ) -> TableGenRecordRef;
}
unsafe extern "C" {
    pub fn tableGenRecordKeeperGetDef(
        rk_ref: TableGenRecordKeeperRef,
        name: TableGenStringRef,
    ) -> TableGenRecordRef;
}
unsafe extern "C" {
    pub fn tableGenRecordKeeperGetAllDerivedDefinitions(
        rk_ref: TableGenRecordKeeperRef,
        className: TableGenStringRef,
    ) -> TableGenRecordVectorRef;
}
unsafe extern "C" {
    pub fn tableGenRecordVectorGet(
        vec_ref: TableGenRecordVectorRef,
        index: usize,
    ) -> TableGenRecordRef;
}
unsafe extern "C" {
    pub fn tableGenRecordVectorFree(vec_ref: TableGenRecordVectorRef);
}
unsafe extern "C" {
    pub fn tableGenRecordKeeperGetFirstClass(
        rk_ref: TableGenRecordKeeperRef,
    ) -> TableGenRecordKeeperIteratorRef;
}
unsafe extern "C" {
    pub fn tableGenRecordKeeperGetFirstDef(
        rk_ref: TableGenRecordKeeperRef,
    ) -> TableGenRecordKeeperIteratorRef;
}
unsafe extern "C" {
    pub fn tableGenRecordKeeperGetNextClass(item: *mut TableGenRecordKeeperIteratorRef);
}
unsafe extern "C" {
    pub fn tableGenRecordKeeperGetNextDef(item: *mut TableGenRecordKeeperIteratorRef);
}
unsafe extern "C" {
    pub fn tableGenRecordKeeperItemGetName(
        item: TableGenRecordKeeperIteratorRef,
    ) -> TableGenStringRef;
}
unsafe extern "C" {
    pub fn tableGenRecordKeeperItemGetRecord(
        item: TableGenRecordKeeperIteratorRef,
    ) -> TableGenRecordRef;
}
unsafe extern "C" {
    pub fn tableGenRecordKeeperIteratorFree(item: TableGenRecordKeeperIteratorRef);
}
unsafe extern "C" {
    pub fn tableGenRecordKeeperIteratorClone(
        item: TableGenRecordKeeperIteratorRef,
    ) -> TableGenRecordKeeperIteratorRef;
}
unsafe extern "C" {
    pub fn tableGenRecordGetRecords(record_ref: TableGenRecordRef) -> TableGenRecordKeeperRef;
}
unsafe extern "C" {
    pub fn tableGenRecordGetName(record_ref: TableGenRecordRef) -> TableGenStringRef;
}
unsafe extern "C" {
    pub fn tableGenRecordGetValue(
        record_ref: TableGenRecordRef,
        name: TableGenStringRef,
    ) -> TableGenRecordValRef;
}
unsafe extern "C" {
    pub fn tableGenRecordGetFieldType(
        record_ref: TableGenRecordRef,
        name: TableGenStringRef,
    ) -> TableGenRecTyKind::Type;
}
unsafe extern "C" {
    pub fn tableGenRecordIsAnonymous(record_ref: TableGenRecordRef) -> TableGenBool;
}
unsafe extern "C" {
    pub fn tableGenRecordIsSubclassOf(
        record_ref: TableGenRecordRef,
        name: TableGenStringRef,
    ) -> TableGenBool;
}
unsafe extern "C" {
    pub fn tableGenRecordPrint(
        record_ref: TableGenRecordRef,
        callback: TableGenStringCallback,
        userData: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn tableGenRecordDump(record_ref: TableGenRecordRef);
}
unsafe extern "C" {
    pub fn tableGenRecordGetLoc(record_ref: TableGenRecordRef) -> TableGenSourceLocationRef;
}
unsafe extern "C" {
    pub fn tableGenRecordValGetName(rv_ref: TableGenRecordValRef) -> TableGenStringRef;
}
unsafe extern "C" {
    pub fn tableGenRecordValGetNameInit(rv_ref: TableGenRecordValRef) -> TableGenTypedInitRef;
}
unsafe extern "C" {
    pub fn tableGenRecordValGetType(rv_ref: TableGenRecordValRef) -> TableGenRecTyKind::Type;
}
unsafe extern "C" {
    pub fn tableGenRecordValGetValue(rv_ref: TableGenRecordValRef) -> TableGenTypedInitRef;
}
unsafe extern "C" {
    pub fn tableGenRecordValTest(rv_ref: TableGenRecordValRef);
}
unsafe extern "C" {
    pub fn tableGenRecordGetFirstValue(record_ref: TableGenRecordRef) -> TableGenRecordValRef;
}
unsafe extern "C" {
    pub fn tableGenRecordValNext(
        record: TableGenRecordRef,
        current: TableGenRecordValRef,
    ) -> TableGenRecordValRef;
}
unsafe extern "C" {
    pub fn tableGenRecordValPrint(
        rv_ref: TableGenRecordValRef,
        callback: TableGenStringCallback,
        userData: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn tableGenRecordValDump(rv_ref: TableGenRecordValRef);
}
unsafe extern "C" {
    pub fn tableGenRecordValGetLoc(rv_ref: TableGenRecordValRef) -> TableGenSourceLocationRef;
}
unsafe extern "C" {
    pub fn tableGenRecordValGetValAsNewString(
        rv_ref: TableGenRecordValRef,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn tableGenRecordValGetValAsBit(rv_ref: TableGenRecordValRef, bit: *mut i8)
    -> TableGenBool;
}
unsafe extern "C" {
    pub fn tableGenRecordValGetValAsBits(rv_ref: TableGenRecordValRef, len: *mut usize) -> *mut i8;
}
unsafe extern "C" {
    pub fn tableGenRecordValGetValAsInt(
        rv_ref: TableGenRecordValRef,
        integer: *mut i64,
    ) -> TableGenBool;
}
unsafe extern "C" {
    pub fn tableGenRecordValGetValAsRecord(rv_ref: TableGenRecordValRef) -> TableGenRecordRef;
}
unsafe extern "C" {
    pub fn tableGenRecordValGetValAsDefRecord(rv_ref: TableGenRecordValRef) -> TableGenRecordRef;
}
unsafe extern "C" {
    pub fn tableGenListRecordGetType(rv_ref: TableGenRecordValRef) -> TableGenRecTyKind::Type;
}
unsafe extern "C" {
    pub fn tableGenListRecordGet(
        rv_ref: TableGenTypedInitRef,
        index: usize,
    ) -> TableGenTypedInitRef;
}
unsafe extern "C" {
    pub fn tableGenListRecordNumElements(rv_ref: TableGenTypedInitRef) -> usize;
}
unsafe extern "C" {
    pub fn tableGenDagRecordOperator(rv_ref: TableGenTypedInitRef) -> TableGenRecordRef;
}
unsafe extern "C" {
    pub fn tableGenDagRecordGet(rv_ref: TableGenTypedInitRef, index: usize)
    -> TableGenTypedInitRef;
}
unsafe extern "C" {
    pub fn tableGenDagRecordArgName(
        rv_ref: TableGenTypedInitRef,
        index: usize,
    ) -> TableGenStringRef;
}
unsafe extern "C" {
    pub fn tableGenDagRecordNumArgs(rv_ref: TableGenTypedInitRef) -> usize;
}
unsafe extern "C" {
    pub fn tableGenInitRecType(ti: TableGenTypedInitRef) -> TableGenRecTyKind::Type;
}
unsafe extern "C" {
    pub fn tableGenBitInitGetValue(ti: TableGenTypedInitRef, bit: *mut i8) -> TableGenBool;
}
unsafe extern "C" {
    pub fn tableGenBitsInitGetValue(ti: TableGenTypedInitRef, len: *mut usize) -> *mut i8;
}
unsafe extern "C" {
    pub fn tableGenBitsInitGetNumBits(ti: TableGenTypedInitRef, len: *mut usize) -> TableGenBool;
}
unsafe extern "C" {
    pub fn tableGenBitsInitGetBitInit(
        ti: TableGenTypedInitRef,
        index: usize,
    ) -> TableGenTypedInitRef;
}
unsafe extern "C" {
    pub fn tableGenIntInitGetValue(ti: TableGenTypedInitRef, integer: *mut i64) -> TableGenBool;
}
unsafe extern "C" {
    pub fn tableGenStringInitGetValue(ti: TableGenTypedInitRef) -> TableGenStringRef;
}
unsafe extern "C" {
    pub fn tableGenStringInitGetValueNewString(
        ti: TableGenTypedInitRef,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn tableGenDefInitGetValue(ti: TableGenTypedInitRef) -> TableGenRecordRef;
}
unsafe extern "C" {
    pub fn tableGenInitPrint(
        ti: TableGenTypedInitRef,
        callback: TableGenStringCallback,
        userData: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn tableGenInitDump(ti: TableGenTypedInitRef);
}
unsafe extern "C" {
    pub fn tableGenPrintError(
        ref_: TableGenParserRef,
        loc_ref: TableGenSourceLocationRef,
        dk: TableGenDiagKind::Type,
        message: TableGenStringRef,
        callback: TableGenStringCallback,
        userData: *mut ::std::os::raw::c_void,
    ) -> TableGenBool;
}
unsafe extern "C" {
    pub fn tableGenSourceLocationNull() -> TableGenSourceLocationRef;
}
unsafe extern "C" {
    pub fn tableGenSourceLocationClone(
        loc_ref: TableGenSourceLocationRef,
    ) -> TableGenSourceLocationRef;
}
unsafe extern "C" {
    pub fn tableGenSourceLocationFree(loc_ref: TableGenSourceLocationRef);
}
unsafe extern "C" {
    pub fn tableGenBitArrayFree(bit_array: *mut i8);
}
unsafe extern "C" {
    pub fn tableGenStringFree(str_: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn tableGenStringArrayFree(str_array: *mut *const ::std::os::raw::c_char);
}
