[package]
authors                = ["Tracel Technologies Inc."]
categories             = ["api-bindings"]
description            = "Rust bindings for MLIR libraries used by CubeCL."
edition.workspace      = true
keywords               = ["cubecl", "llvm", "mlir", "bindings"]
license                = "Apache-2.0"
name                   = "tracel-mlir-rs-macros"
readme.workspace       = true
repository             = "https://github.com/tracel-ai/tracel-llvm/tree/main/crates/tracel-mlir-rs-macros"
rust-version.workspace = true
version.workspace      = true

[lib]
proc-macro = true

[dependencies]
comrak = { version = "0.39.1", default-features = false }
convert_case = "0.8.0"
proc-macro2 = "1"
quote = "1"
regex = "1.11.2"
syn = { version = "2", features = ["full"] }
tracel-llvm-bundler = { path = "../tracel-llvm-bundler", version = "20.1.4-3" }
tracel-tblgen-rs = { path = "../tracel-tblgen-rs", version = "20.1.4-3" }
unindent = "0.2.4"

[dev-dependencies]
pretty_assertions = "1.4.1"
# crates.io verifier wants to take into account dev-dependencies no matter what
# this is not possible here because this introduces a cyclic dependency with tracel-mlir-rs
# tracel-mlir-rs = { path = "../tracel-mlir-rs", version = "20.1.4-3", features = ["ods-dialects"] }

[build-dependencies]
tracel-llvm-bundler = { path = "../tracel-llvm-bundler", version = "20.1.4-3" }
