[package]
authors                = ["Tracel Technologies Inc."]
categories             = ["api-bindings"]
description            = "Rust bindings for MLIR libraries used by CubeCL."
edition                = "2021"
keywords               = ["cubecl", "llvm", "mlir", "bindings"]
license                = "Apache-2.0"
name                   = "tracel-mlir-rs"
readme.workspace       = true
repository             = "https://github.com/tracel-ai/tracel-llvm/tree/main/crates/tracel-mlir-rs"
rust-version.workspace = true
version.workspace      = true

[features]
ods-dialects = []
# Enable the BlockExt trait (requires ods feature)
helpers = ["ods-dialects"]

[dependencies]
tracel-mlir-rs-macro = { path = "../tracel-mlir-rs-macro" }
tracel-mlir-sys = { path = "../tracel-mlir-sys" }

[dev-dependencies]
indoc = "2.0.6"
insta = "1.43.1"
pretty_assertions = "1.4.1"
