[package]
name = "mlir-rs"
description = "MLIR bindings in Rust for Tracel projects"
version = "0.24.0"
edition = "2021"
license = "Apache-2.0"
keywords = ["mlir", "llvm"]
categories = ["api-bindings"]

[features]
ods-dialects = []
# Enable the BlockExt trait (requires ods feature)
helpers = ["ods-dialects"]

[dependencies]
mlir-rs-macro = { path = "../mlir-rs-macro" }
mlir-sys = { path = "../mlir-sys" }

[dev-dependencies]
indoc = "2.0.6"
insta = "1.43.1"
pretty_assertions = "1.4.1"
