name: Publish Release

on:
  workflow_dispatch:
    inputs:
      dry-run-only:
        description: "Run xtask publish in dry-run mode (no publish)"
        type: boolean
        required: false
        default: false

jobs:
  versions:
    runs-on: ubuntu-22.04
    outputs:
      llvm_version: ${{ steps.read_config.outputs.llvm_version }}
      release_number: ${{ steps.read_config.outputs.release_number }}
      tag: ${{ steps.read_config.outputs.tag }}
    steps:
      - uses: actions/checkout@v6
      - name: Read LLVM release config
        id: read_config
        uses: ./.github/actions/versions

  publish-tracel-llvm-bundler:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v11
    with:
      crate: tracel-llvm-bundler
      tag-validation: false
      dry-run-only: ${{ github.event_name == 'workflow_dispatch' && inputs.dry-run-only || false }}
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  publish-tracel-mlir-sys:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v11
    with:
      crate: tracel-mlir-sys
      tag-validation: false
      dry-run-only: ${{ github.event_name == 'workflow_dispatch' && inputs.dry-run-only || false }}
    needs:
      - publish-tracel-llvm-bundler
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  publish-tracel-tblgen-rs:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v11
    with:
      crate: tracel-tblgen-rs
      tag-validation: false
      dry-run-only: ${{ github.event_name == 'workflow_dispatch' && inputs.dry-run-only || false }}
    needs:
      - publish-tracel-llvm-bundler
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  publish-tracel-mlir-rs-macros:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v11
    with:
      crate: tracel-mlir-rs-macros
      tag-validation: false
      dry-run-only: ${{ github.event_name == 'workflow_dispatch' && inputs.dry-run-only || false }}
    needs:
      - publish-tracel-llvm-bundler
      - publish-tracel-tblgen-rs
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  publish-tracel-mlir-rs:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v11
    with:
      crate: tracel-mlir-rs
      tag-validation: false
      dry-run-only: ${{ github.event_name == 'workflow_dispatch' && inputs.dry-run-only || false }}
    needs:
      - publish-tracel-mlir-rs-macros
      - publish-tracel-mlir-sys
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  publish-tracel-llvm:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v11
    with:
      crate: tracel-llvm
      tag-validation: false
      dry-run-only: ${{ github.event_name == 'workflow_dispatch' && inputs.dry-run-only || false }}
    needs:
      - publish-tracel-mlir-rs
      - publish-tracel-mlir-sys
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  publish-release:
    needs:
      - versions
      - publish-tracel-llvm
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
      # ----------------------------------------------------------------------
      - name: Make Release public
        id: create_release
        # pin to v2.4.2 for now, see: https://github.com/softprops/action-gh-release/issues/709
        uses: softprops/action-gh-release@v2.4.2
        if: ${{ !inputs.dry-run-only }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ needs.versions.outputs.tag }}
          tag_name: ${{ needs.versions.outputs.tag }}
          draft: false
          prerelease: false
          generate_release_notes: true
          make_latest: false
          append_body: false
