name: Publish

on:
  workflow_dispatch:
    inputs:
      dry-run-only:
        description: "Run xtask publish in dry-run mode (no publish)"
        type: boolean
        required: false
        default: false

jobs:
  publish-tracel-llvm-bundler:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v11
    with:
      crate: tracel-llvm-bundler
      tag-validation: false
      dry-run-only: ${{ github.event_name == 'workflow_dispatch' && inputs.dry-run-only || false }}
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  publish-tracel-mlir-sys:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v11
    with:
      crate: tracel-mlir-sys
      tag-validation: false
      dry-run-only: ${{ github.event_name == 'workflow_dispatch' && inputs.dry-run-only || false }}
    needs:
      - publish-tracel-llvm-bundler
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  publish-tracel-tblgen-rs:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v11
    with:
      crate: tracel-tblgen-rs
      tag-validation: false
      dry-run-only: ${{ github.event_name == 'workflow_dispatch' && inputs.dry-run-only || false }}
    needs:
      - publish-tracel-llvm-bundler
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  publish-tracel-mlir-rs-macros:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v11
    with:
      crate: tracel-mlir-rs-macros
      tag-validation: false
      dry-run-only: ${{ github.event_name == 'workflow_dispatch' && inputs.dry-run-only || false }}
    needs:
      - publish-tracel-llvm-bundler
      - publish-tracel-tblgen-rs
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  publish-tracel-mlir-rs:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v11
    with:
      crate: tracel-mlir-rs
      tag-validation: false
      dry-run-only: ${{ github.event_name == 'workflow_dispatch' && inputs.dry-run-only || false }}
    needs:
      - publish-tracel-mlir-rs-macros
      - publish-tracel-mlir-sys
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  publish-tracel-llvm:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v11
    with:
      crate: tracel-llvm
      tag-validation: false
      dry-run-only: ${{ github.event_name == 'workflow_dispatch' && inputs.dry-run-only || false }}
    needs:
      - publish-tracel-mlir-rs
      - publish-tracel-mlir-sys
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}
