name: Publish

on:
  workflow_dispatch:

jobs:
  publish-tracel-llvm-bundler:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v4
    with:
      crate: tracel-llvm-bundler
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  publish-tracel-mlir-sys:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v4
    with:
      crate: tracel-mlir-sys
    needs:
      - publish-tracel-llvm-bundler
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  publish-tracel-tblgen-rs:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v4
    with:
      crate: tracel-tblgen-rs
    needs:
      - publish-tracel-llvm-bundler
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  publish-tracel-mlir-rs-macros:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v4
    with:
      crate: tracel-mlir-rs-macros
    needs:
      - publish-tracel-llvm-bundler
      - publish-tracel-tblgen-rs
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  publish-tracel-mlir-rs:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v4
    with:
      crate: tracel-mlir-rs
    needs:
      - publish-tracel-mlir-rs-macros
      - publish-tracel-mlir-sys
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  publish-tracel-llvm:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v4
    with:
      crate: tracel-llvm
    needs:
      - publish-tracel-mlir-rs
      - publish-tracel-mlir-sys
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}
