name: Publish Crates

on:
  workflow_dispatch:
    inputs:
      dry-run-only:
        description: "Run xtask publish in dry-run mode (no publish)"
        type: boolean
        required: false
        default: false

jobs:
  publish-tracel-llvm-bundler:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v11
    with:
      crate: tracel-llvm-bundler
      tag-validation: false
      dry-run-only: ${{ github.event_name == 'workflow_dispatch' && inputs.dry-run-only || false }}
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}
