name: Build and Release LLVM

on:
  workflow_dispatch:
    inputs:
      llvm_version:
        description: "LLVM version (e.g. 21.1.0)"
        required: true
        type: string
      # increment the release number if we publish multiple releases for the same llvm_version
      release_number:
        description: "Release number (will be suffixed to llvm_version)"
        default: "1"
        required: true
        type: string

jobs:
  create-release:
    runs-on: ubuntu-22.04
    outputs:
      tag: ${{ steps.compute_tag.outputs.tag }}
      upload_url: ${{ steps.get_upload_url.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v5
      # ----------------------------------------------------------------------
      - name: Compute tag
        id: compute_tag
        run: echo "tag=v${{ inputs.llvm_version }}-${{ inputs.release_number }}" >> "$GITHUB_OUTPUT"
      # ----------------------------------------------------------------------
      - name: Create Release
        id: create_release
        uses: elgohr/Github-Release-Action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ steps.compute_tag.outputs.tag }}
          title: ${{ steps.compute_tag.outputs.tag }}
          prerelease: false
      # ----------------------------------------------------------------------
      - name: Get upload_url
        id: get_upload_url
        run: |
          URL=$(gh release view "${{ steps.compute_tag.outputs.tag }}" --json uploadUrl -q .uploadUrl)
          echo "upload_url=$URL" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  llvm-linux:
    needs: create-release
    runs-on: [
      '@id:llvm-linux-job-${{ github.run_id }}-${{ github.run_attempt }}',
      # Older Ubuntu to build with a more ancient libc to support more platforms
      '@image-family:ubuntu-2204-lts',
      '@image-project:ubuntu-os-cloud',
      '@disk-size:100',
      '@keep-alive:true',
      '@machine-type:n2-standard-48',
      '@os:linux',
      '@zone:northamerica-northeast1-b'
      ]
    steps:
      - uses: actions/checkout@v5
      # ----------------------------------------------------------------------
      - name: Build LLVM
        run: bash build_llvm.sh
      # ----------------------------------------------------------------------
      - name: Upload Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: .llvm/linux-x64.tar.xz
          asset_name: llvm-linux-x64.tar.xz
          asset_content_type: application/x-xz

  llvm-macos:
    needs: create-release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      # ----------------------------------------------------------------------
      - name: Build LLVM
        run: bash build_llvm.sh
      # ----------------------------------------------------------------------
      - name: Upload Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: .llvm/macos-AArch64.tar.xz
          asset_name: llvm-macos-AArch64.tar.xz
          asset_content_type: application/x-xz

  llvm-windows:
    needs: create-release
    runs-on: [
      '@id:llvm-windows-job-${{ github.run_id }}-${{ github.run_attempt }}',
      '@image-family:windows-2022',
      '@image-project:windows-cloud',
      '@disk-size:100',
      '@keep-alive:false',
      '@machine-type:n2-standard-48',
      '@os:windows',
      '@zone:northamerica-northeast1-b'
      ]
    steps:
      - uses: actions/checkout@v5
      # ----------------------------------------------------------------------
      - name: Build LLVM
        shell: pwsh
        run: ./build_llvm.ps1 -Version ${{ inputs.llvm_version }}
      # ----------------------------------------------------------------------
      - name: Upload Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: windows-x64.tar.xz
          asset_name: llvm-windows-x64.tar.xz
          asset_content_type: application/x-xz
