name: Build and Release LLVM

on:
  workflow_dispatch:
    inputs:
      llvm_version:
        description: "LLVM version (e.g. 21.1.0)"
        required: true
        type: string

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-22.04
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.llvm_version }}
          release_name: LLVM Release ${{ inputs.llvm_version }}
          draft: false
          prerelease: false

  llvm-linux:
    needs: create-release
    # Building on a older Ubuntu to build with a more ancient libc to support more platforms
    runs-on: [
      '@id:llvm-linux-job-${{ github.run_id }}-${{ github.run_attempt }}',
      '@image-family:ubuntu-2204-lts',
      '@image-project:ubuntu-os-cloud',
      '@disk-size:100',
      '@keep-alive:true',
      '@machine-type:n2-standard-48',
      '@os:linux',
      '@zone:northamerica-northeast1-b'
      ]
    steps:
      - uses: actions/checkout@v4
      # ----------------------------------------------------------------------
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build xz-utils git
      # ----------------------------------------------------------------------
      - name: Build LLVM
        run: bash build_llvm.sh
      # ----------------------------------------------------------------------
      - name: Upload Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: linux-x64.tar.xz
          asset_name: llvm-linux-x64.tar.xz
          asset_content_type: application/x-xz

  # llvm-macos:
  #   needs: create-release
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     # ----------------------------------------------------------------------
  #     - name: Install dependencies
  #       run: brew install cmake ninja xz
  #     # ----------------------------------------------------------------------
  #     - name: Build LLVM
  #       run: bash build_llvm.sh
  #     # ----------------------------------------------------------------------
  #     - name: Upload Release
  #       uses: actions/upload-release-asset@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         upload_url: ${{ needs.create-release.outputs.upload_url }}
  #         asset_path: macos-AArch64.tar.xz
  #         asset_name: llvm-macos-AArch64.tar.xz
  #         asset_content_type: application/x-xz

  llvm-windows:
    needs: create-release
    runs-on: [
      '@id:llvm-windows-job-${{ github.run_id }}-${{ github.run_attempt }}',
      '@image-family:windows-2022',
      '@image-project:windows-cloud',
      '@disk-size:100',
      '@keep-alive:false',
      '@machine-type:n2-standard-48',
      '@os:windows',
      '@zone:northamerica-northeast1-b'
      ]
    steps:
      - uses: actions/checkout@v4
      # ----------------------------------------------------------------------
      - name: Build LLVM
        shell: pwsh
        run: ./build_llvm.ps1 -Version ${{ inputs.llvm_version }}
      # ----------------------------------------------------------------------
      - name: Upload Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: windows-x64.tar.xz
          asset_name: llvm-windows-x64.tar.xz
          asset_content_type: application/x-xz
