name: Release

on:
  workflow_dispatch:

# The LLVM version and release numbers are set in the file `crates/tracel-llvm-bundler/src/config.rs`:
# pub const TRACEL_LLVM_VERSION: &str = "20.1.4";
# pub const TRACEL_LLVM_RELEASE_NUMBER: &str = "6";

jobs:
  create-release:
    runs-on: ubuntu-22.04
    outputs:
      llvm_version: ${{ steps.read_config.outputs.llvm_version }}
      release_number: ${{ steps.read_config.outputs.release_number }}
      tag: ${{ steps.compute_tag.outputs.tag }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v6
      # ----------------------------------------------------------------------
      - name: Read LLVM version from config.rs
        id: read_config
        shell: bash
        run: |
          CONFIG_FILE="crates/tracel-llvm-bundler/src/config.rs"

          llvm_version=$(sed -n 's/.*TRACEL_LLVM_VERSION: &str = "\(.*\)";/\1/p' "$CONFIG_FILE")
          release_number=$(sed -n 's/.*TRACEL_LLVM_RELEASE_NUMBER: &str = "\(.*\)";/\1/p' "$CONFIG_FILE")

          if [[ -z "$llvm_version" || -z "$release_number" ]]; then
            echo "Failed to extract LLVM version or release number from config.rs"
            exit 1
          fi

          echo "llvm_version=$llvm_version" >> "$GITHUB_OUTPUT"
          echo "release_number=$release_number" >> "$GITHUB_OUTPUT"
      # ----------------------------------------------------------------------
      - name: Compute tag
        id: compute_tag
        shell: bash
        run: |
          echo "tag=v${{ steps.read_config.outputs.llvm_version }}-${{ steps.read_config.outputs.release_number }}" >> "$GITHUB_OUTPUT"
      # ----------------------------------------------------------------------
      - name: Create Release
        id: create_release
        # pin to v2.4.2 for now, see: https://github.com/softprops/action-gh-release/issues/709
        uses: softprops/action-gh-release@v2.4.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ steps.compute_tag.outputs.tag }}
          tag_name: ${{ steps.compute_tag.outputs.tag }}
          draft: true
          prerelease: false
          generate_release_notes: false
          make_latest: false

  llvm-linux:
    needs: create-release
    strategy:
      matrix:
        arch: ["x86-64", "arm64"]
        include:
          - arch: "x86-64"
            image_family: "ubuntu-2204-lts"
            machine_type: "n2-standard-48"
            gh_arch: "x64"
            zones: "northamerica-northeast1-b"
            suffix: "x64"
          - arch: "arm64"
            image_family: "ubuntu-2204-lts-arm64"
            # always looks for actual zones where the wanted machine type exists
            machine_type: "t2a-standard-48"
            zones: "us-central1-b"
            gh_arch: "arm64"
            suffix: "AArch64"
    runs-on: [
      '@id:llvm-linux-${{ matrix.arch }}-job-${{ github.run_id }}-${{ github.run_attempt }}',
      # Older Ubuntu to build with a more ancient libc to support more platforms
      '@image-family:${{ matrix.image_family }}',
      '@image-project:ubuntu-os-cloud',
      '@disk-size:100',
      '@keep-alive:false',
      '@machine-type:${{ matrix.machine_type }}',
      '@os:linux',
      '@architecture:${{ matrix.gh_arch }}',
      '@zones:${{ matrix.zones }}'
      ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      # ----------------------------------------------------------------------
      - name: Install pre-reqs
        shell: bash
        run: |
          bash scripts/install-prereqs.sh
      # ----------------------------------------------------------------------
      - name: Setup Rust
        uses: tracel-ai/github-actions/install-rust@v11
        with:
          rust-toolchain: stable
          cache-key: stable-linux-${{ matrix.suffix }}
      # ----------------------------------------------------------------------
      - name: Build LLVM bunlde
        run: xtask bundle build
      # ----------------------------------------------------------------------
      - name: Upload Release
        # pin to v2.4.2 for now, see: https://github.com/softprops/action-gh-release/issues/709
        uses: softprops/action-gh-release@v2.4.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ needs.create-release.outputs.tag }}
          tag_name: ${{ needs.create-release.outputs.tag }}
          files: |
            .llvm/linux-${{ matrix.suffix }}.tar.xz
            .llvm/linux-${{ matrix.suffix }}.checksums.json

  llvm-macos:
    needs: create-release
    runs-on: blaze/macos-15
    steps:
      - uses: actions/checkout@v6
      # ----------------------------------------------------------------------
      - name: Install pre-reqs
        shell: bash
        run: |
          bash scripts/install-prereqs.sh
      # ----------------------------------------------------------------------
      - name: Setup Rust
        uses: tracel-ai/github-actions/install-rust@v11
        with:
          rust-toolchain: stable
          cache-key: stable-macos
      # ----------------------------------------------------------------------
      - name: Build LLVM bunlde
        run: xtask bundle build
      # ----------------------------------------------------------------------
      - name: Upload Release
        # pin to v2.4.2 for now, see: https://github.com/softprops/action-gh-release/issues/709
        uses: softprops/action-gh-release@v2.4.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ needs.create-release.outputs.tag }}
          tag_name: ${{ needs.create-release.outputs.tag }}
          files: |
            .llvm/macos-AArch64.tar.xz
            .llvm/macos-AArch64.checksums.json

  llvm-windows:
    needs: create-release
    runs-on: [
      '@id:llvm-windows-job-${{ github.run_id }}-${{ github.run_attempt }}',
      '@image-family:windows-2022',
      '@image-project:windows-cloud',
      '@disk-size:100',
      '@keep-alive:false',
      '@machine-type:n2-standard-48',
      '@os:windows',
      '@zones:northamerica-northeast1-b'
      ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      # ----------------------------------------------------------------------
      - name: Install pre-reqs
        shell: pwsh
        run: |
          pwsh -ExecutionPolicy Bypass -File scripts/install-prereqs.ps1
      # ----------------------------------------------------------------------
      - name: Install xtask CLI
        shell: pwsh
        run: |
          cargo install tracel-xtask-cli
      # ----------------------------------------------------------------------
      - name: Build LLVM bundle
        shell: pwsh
        run: |
          $vsDevCmd = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2022\BuildTools\Common7\Tools\VsDevCmd.bat"
          cmd /v:on /c "`"$vsDevCmd`" -arch=x64 && where cl && where cmake && xtask bundle build"
      # ----------------------------------------------------------------------
      - name: Upload Release
        # pin to v2.4.2 for now, see: https://github.com/softprops/action-gh-release/issues/709
        uses: softprops/action-gh-release@v2.4.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ needs.create-release.outputs.tag }}
          tag_name: ${{ needs.create-release.outputs.tag }}
          files: |
            .llvm/windows-x64.tar.xz
            .llvm/windows-x64.checksums.json

  publish-release:
    # needs: [create-release, llvm-linux, llvm-macos, llvm-windows]
    needs: [create-release, llvm-linux, llvm-windows]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
      # ----------------------------------------------------------------------
      - name: Make Release the latest one
        id: create_release
        # pin to v2.4.2 for now, see: https://github.com/softprops/action-gh-release/issues/709
        uses: softprops/action-gh-release@v2.4.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ needs.create-release.outputs.tag }}
          tag_name: ${{ needs.create-release.outputs.tag }}
          draft: false
          prerelease: false
          generate_release_notes: true
          make_latest: false
          append_body: false
